### ISSUE TITLE
Use version 2.0 instead of 1.1 

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-syntax#10]
[Comments at TPAC](https://json-ld.org/minutes/2017-11-08/) suggested that as our work is a breaking change (causing 1.0 processors that are not 1.1 compatible to intentionally break when they see `"@version": 1.1`), [semantic versioning](http://semver.org) would suggest that we use a major release number, rather than a minor number.

Original issue is [Use version 2.0 instead of 1.1 #548](https://github.com/json-ld/json-ld.org/issues/548)

**Comment by azaroth42** [comment]
Yup, agree with closing. Charter is pretty clear on backwards compatibility.

**Comment by azaroth42** [comment]
Closing, won't fix. Rationale: We're not chartered to make breaking changes.

WG Resolution: https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-07-27-json-ld#section2-3
