### ISSUE TITLE
expansion does not associate keys to ids

### ISSUE THREAD

**Issue by satra** [w3c/json-ld-syntax#101]
Expanded form of this example:
```json
{
  "@context": {
    "@version": 1.1,
    "ui_order": {
     "@id": "https://schema.repronim.org/ui_order",
     "@container": "@list",
     "@type": "@id"
    },
    "phq9_1": {
      "@id": "https://schema.repronim.org/phq9_1.jsonld",
      "@type": "@id"
    },
    "phq9_2": {
      "@id": "https://schema.repronim.org/phq9_2.jsonld",
      "@type": "@id"
    }
  },
  "ui_order": [
    "phq9_1",
    "phq9_2"]
}
```

returns:

```json
[{"https://schema.repronim.org/ui_order": 
    [{"@list": [{"@id": "https://json-ld.org/playground-dev/phq9_1"},
                {"@id": "https://json-ld.org/playground-dev/phq9_2"}
]}]}]
```

we were expecting that the URIs would be the ID's in the keys instead of the playground prefix. are we interpreting something incorrectly?

[Playground link](https://json-ld.org/playground-dev/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22ui_order%22%3A%7B%22%40id%22%3A%22https%3A%2F%2Fschema.repronim.org%2Fui_order%22%2C%22%40container%22%3A%22%40list%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22phq9_1%22%3A%7B%22%40id%22%3A%22https%3A%2F%2Fschema.repronim.org%2Fphq9_1.jsonld%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22phq9_2%22%3A%7B%22%40id%22%3A%22https%3A%2F%2Fschema.repronim.org%2Fphq9_2.jsonld%22%2C%22%40type%22%3A%22%40id%22%7D%7D%2C%22ui_order%22%3A%5B%22phq9_1%22%2C%22phq9_2%22%5D%7D&frame=%7B%22ui_order%22%3A%7B%22%40type%22%3A%22https%3A%2F%2Fraw.githubusercontent.com%2Fsanuann%2Fschema-standardization%2Fmaster%2Fschemas%2FField.jsonld%22%2C%22%40explicit%22%3Atrue%7D%7D&context=%7B%7D)

we could of course do this to make the URLs in this case explicit, but trying to figure out how keys defined in context are interpreted:

```json
{
  "@context": {
    "@version": 1.1,
    "ui_order": {
     "@id": "https://schema.repronim.org/ui_order",
     "@container": "@list",
     "@type": "@id"
    },
    "rs": "https://schema.repronim.org/"
  },
  "ui_order": [
    "rs:phq9_1.jsonld",
    "rs:phq9_2.jsonld"]
}
```

cc: @sanuann

**Comment by gkellogg** [comment]
Values of type `@id` are document relative, not vocabulary relative. Using `rs:ph9...` works in either case, but to have `phq9...` considered from the vocabulary, use `"@type": "@vocab"`.

See [this playground link](https://json-ld.org/playground-dev/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22ui_order%22%3A%7B%22%40id%22%3A%22https%3A%2F%2Fschema.repronim.org%2Fui_order%22%2C%22%40container%22%3A%22%40list%22%2C%22%40type%22%3A%22%40vocab%22%7D%2C%22phq9_1%22%3A%7B%22%40id%22%3A%22https%3A%2F%2Fschema.repronim.org%2Fphq9_1.jsonld%22%2C%22%40type%22%3A%22%40id%22%7D%2C%22phq9_2%22%3A%7B%22%40id%22%3A%22https%3A%2F%2Fschema.repronim.org%2Fphq9_2.jsonld%22%2C%22%40type%22%3A%22%40id%22%7D%7D%2C%22ui_order%22%3A%5B%22phq9_1%22%2C%22phq9_2%22%5D%7D).

**Comment by satra** [comment]
thank you @gkellogg

**Comment by sanuann** [comment]
Thank you @gkellogg
