### ISSUE TITLE
Add SPARQL to the section I 

### ISSUE THREAD

**Issue by PaulJeong14** [w3c/json-ld-syntax#109]
In the introduction section, SPARQL is referred like below. 

> JSON-LD is designed to be usable directly as JSON, with no knowledge of RDF [RDF11-CONCEPTS]. It is also designed to be usable as RDF, if desired, for use with other Linked Data technologies like SPARQL. 

But no reference for that in section I.  
I suggest putting the SPARQL(https://www.w3.org/TR/sparql11-query/) standard into the section I as an informative reference.

**Comment by pchampin** [comment]
I agree that an informative reference is required. However, I think SPARQL Overview (https://www.w3.org/TR/sparql11-overview/) would be a better entry point.

**Comment by akuckartz** [comment]
Both ;-)

**Comment by PaulJeong14** [comment]
Ok. anything will be fine with me.

**Comment by BigBlueHat** [comment]
Closing this one as fixed per 6f92b1d. Thanks for the request @PaulJeong14 and for the quick work @pchampin!
