### ISSUE TITLE
What if a sealed context sets `@vocab`?

### ISSUE THREAD

**Issue by pchampin** [w3c/json-ld-syntax#120]
Consider the following context
```json
{
  "@context": {
    "@vocab": "http://schema.org/"
  }
}
```
Basically, it provides a blanket interpretation for any term. Now, what if I add `"@sealed":true` in that context? Should it prevent further contexts to redefine *any* term at all? And, of course, to reset `@vocab` to another value?

I don't think that the use-cases addressed by sealed contexts require the functionality offered by `@vocab`. In my view, only the *term definitions* of a sealed context are sealed, not the `@vocab`. As such, if a sealed context defines `@vocab`, it would probably be useful to issue a warning explaining that, unless the rest of the sealed context, `@vocab` might be overridden.

**Comment by gkellogg** [comment]
IIRC, we discussed this and sealing would only involve terms, not `@vocab`, `@language`, or `@base`.

**Comment by iherman** [comment]
> IIRC, we discussed this and sealing would only involve terms, not @vocab, @language, or @base.

What about `@container`? I would expect sealing this one might make a lot of sense for the use cases we discussed...

**Comment by gkellogg** [comment]
I was referring to non-term members of the context, not members of a term definition. Sealing a term seals all the members of the term.

**Comment by gkellogg** [comment]
From merged change, contexts aren't sealed, terms are sealed, so there is no affect on `@vocab`.

**Comment by azaroth42** [comment]
Closing, given above.
