### ISSUE TITLE
Graph container text and implementation do not match...

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-syntax#122]
The text underneath https://w3c.github.io/json-ld-syntax/#ex-88-implicitly-named-graph says:

> The example above expresses a named graph that is identified by the blank node identifier _:b0. That graph is composed of the statements about Manu and Gregg. Metadata about the graph itself is expressed via the generatedAt property, which specifies when the graph was generated.

This seems to be wrong. The playground result, as well as the text above the example suggests that it should say something like:

> The example above expresses two named graphs, identified by blank nodes. These graphs are composed of the statements about Manu and Gregg, respectively, each in its own separate graphs. 

Strictly speaking, the `generatedAt` is about a _resource_ (`http://example.org/foaf-graph`) which is not a dataset/graph, "just" a resource.

We may want to spend some time looking over the whole section...

**Comment by gkellogg** [comment]
Yes, you're correct. This was based on [example 85](https://w3c.github.io/json-ld-syntax/#example-85-identifying-and-making-statements-about-a-graph), which names the graph as "http://example.org/foaf-graph", and there is, in fact, only one named graph.

We should probably change the example more completely to not give the wrong impression. @dlongley, perhaps there's something from claims that might be introduced here.
