### ISSUE TITLE
IRI expansions in the context... a bit messy:-(

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-syntax#123]
While re-reading the syntax document I got to [example 36](https://w3c.github.io/json-ld-syntax/#example-36-using-a-compact-iri-as-a-term) and [example 37](https://w3c.github.io/json-ld-syntax/#example-37-associating-context-definitions-with-absolute-iris) and I must admit it is still a mystery to me. I wonder whether this is purely editorial and can be explained better or whether it _is_ messy.

If the latter, we may want to consider revising this part of the algorithm and possibly disallowing certain combination. As it stands, this is the type of complication that may drive away people from JSON-LD... ☹️

**Comment by pchampin** [comment]
I agree, it feels like example 36 should look like
```
{
  "@context": {
    "foaf": "http://xmlns.com/foaf/0.1/",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "name": "foaf:name",
    "foaf:age": {
      "@id": "http://xmlns.com/foaf/0.1/age",  <<<<< isn't this line missing?
      "@type": "xsd:integer"
    },
    "foaf:homepage": {
      "@type": "@id"
    }
  },
  ...
}
```

**Comment by gkellogg** [comment]
The `@id` isn't necessary in `foaf:age`, as it is in a compact IRI form, and it's ID can be determined. This may require some additional description, though.

**Comment by pchampin** [comment]
Gregg Kellogg wrote:

> The @id isn't necessary in foaf:age, as it is in a compact IRI form, and
> it's ID can be determined.
>
Yes, but I thought that was was the text after the example was describing...

> This may require some additional description, though.
>
Indeed. I don't grasp the difference between foaf:age and foaf:homepage
that the text is supposed to highlight.

**Comment by gkellogg** [comment]
Just above example 36 it says the following:

> Compact IRIs and IRIs may be used on the left-hand side of a term definition.

In this case, `foaf:age` and `foaf:homepage` are such left-hand-side compact IRIs. As it says just below:

> In the first approach, foaf:age declares both the IRI for the term (using short-form) as well as the `@type` associated with the term.

This seems pretty clear to me.

**Comment by gkellogg** [comment]
@iherman said:

> If the latter, we may want to consider revising this part of the algorithm and possibly disallowing certain combination. As it stands, this is the type of complication that may drive away people from JSON-LD...

This is been in since 1.0, and it seems fairly clear to me that when, say, `foaf:age` is used for the key of a term definition, that it implies an `@id`. Removing this, would break current usage and be incompatible with 1.0.

However, I believe the use of compact IRIs as the keys of term definitions is rare, and best practice encourages the use of simple terms (e.g., `age`, and  `homepage`) which is much more idiomatic JSON.

**Comment by pchampin** [comment]
What is not clear to me, in the paragraph following example 36, is what the "first approach" and "second approach" are, and how they differ. The paragraph seems to imply that the term definition of `foaf:age` uses the first approach, and that the term definition of `foaf:homepage` uses the second approach.

> In the first approach, `foaf:age` declares (...) the IRI for the term (using short-form) 

and then

> In the second approach (...) The full IRI for `foaf:homepage` is determined by looking up the foaf prefix in the context. 

For me, both stamements are equally true for both `foaf:age` and `foaf:homepage`...

**Comment by gkellogg** [comment]
Ahh, yes, we should change `foaf:age` to just `age` to make this clear.
