### ISSUE TITLE
TriG graphs in JSON-LD

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-syntax#128]
I just try to test my understanding...

Consider the following TriG dataset:

```
@prefix a <http://example.org/a> .
@prefix b <http://example.org/b> .
@prefix c <http://example.org/c> .

<http://example.org/gr1> {
    a:something a:predicate "value1",
                b:predicate c:something1 .
}
<http://example.org/gr2> {
    a:something a:predicate "value2",
                b:predicate c:something2 .
}
```

The only way to express this in JSON-LD to repeat a `@context`, i.e.,

```json
[
    {
        "@context" : {
            "a": "http://example.org/a",
            "b": "http://example.org/b",
            "c":  "http://example.org/c",
            "b:predicate" : { "@type" : "@id" }
        },
        "@id" : "http://example.org/gr1",
        "@graph" : {
            "@id" : "a:something",
            "a:predicate" : "value1",
            "b:predicate" : "c:something1"
        }
    },
    {
        "@context" : {
            "a": "http://example.org/a",
            "b": "http://example.org/b",
            "c":  "http://example.org/c",
            "b:predicate" : { "@type" : "@id" }
        },
        "@id" : "http://example.org/gr2",
        "@graph" : {
            "@id" : "a:something",
            "a:predicate" : "value2",
            "b:predicate" : "c:something2"
        }
    }
]
```

I.e., the context must be repeated.; there is no way of using a "global" context. I am not sure whether this is a problem in practice, but it may become one if JSON-ID is used for large datasets. In any case, this may have to be documented somewhere because it may not be 100% obvious for a first-time reader (best practices document?).

---

That being said: one way of handling that over the Web is if the server returns

```
[
    {
        "@id" : "http://example.org/gr1",
        "@graph" : {
            "@id" : "a:something",
            "a:predicate" : "value1",
            "b:predicate" : "c:something1"
        }
    },
    {
        "@id" : "http://example.org/gr2",
        "@graph" : {
            "@id" : "a:something",
            "a:predicate" : "value2",
            "b:predicate" : "c:something2"
        }
    }
]
```

and the `@context` is returned via an HTTP Link. According to section 6, the processor is supposed to repeat the context for each element of the array...

**Comment by pchampin** [comment]
... which unfortunately gives the wrong impression that there are three graphs in this dataset. And I'm assuming this is why Ivan didn't naturally came up with this solution.

Wouldn't the following also work?
```json
{
  "@context" : {
    "a": "http://example.org/a",
    "b": "http://example.org/b",
    "c":  "http://example.org/c",
    "b:predicate" : { "@type" : "@id" },
    "graphs": {
      "@id": "@nest",
      "@container": ["@graph", "@id"]
    }
  },
  "graphs": {
    "http://example.org/gr1": {
      "@id": "a:something",
      "a:predicate": "value1",
      "b:predicate": "c:something1"
    },
    "http://example.org/gr2": {
      "@id": "a:something",
      "a:predicate": "value2",
      "b:predicate": "c:something2"
    }
  }
}
```

(the dev playground refuses it, but I'm assuming this is a missing implementations of the `@graph` container feature)...

If so, it might be worthwhile to document this "pattern", which might be more natural for some people?

**Comment by iherman** [comment]
@dlongley indeed, https://github.com/w3c/json-ld-syntax/issues/128#issuecomment-460870217 also works but, just @pchampin remarks, it did not come naturally.

The point is a very long time grudge I have against the current syntax, namely the conflation of the term `@graph` for different usages. The outer level in this solution, in spite of its name, does _not_ define _any_ graph by itself, it is only a syntactic sugar to get around a problem imposed by JSON (and a problem that does not come in Turtle). The same is true when `@graph` is used for a single graph which has several roots (we referred to a 'bush'): it does _not_ define a graph in the RDF dataset term and the result is not really different from the shorter and friendlier way when a tree-like graph is defined.

There is still an open issue (#30) but I do realize this is a battle I am loosing. I was already messed up by the duality of the `@graph` usage in the JSON-LD 1.0 days, and I remember I was not successful either.

@pchampin your example probably works, but shouldn't it be a `"@nest":"graphs"` on the top-level? I did not find a definition (or example) for `"@id":"@nest"` in the spec. But yes, otherwise the idea works, but it is just a (great) fig leaf to hide something that you are not supposed to see...

**Comment by dlongley** [comment]
Yeah, I've never been a fan of overloading `@graph` in this way, but there were concerns about the number of keywords in JSON-LD 1.0 and I think this was compromise that was somewhat awkward but fell out of other algorithms/approaches. Its use was also considered quite rare so less of a concern.

**Comment by gkellogg** [comment]
One thought that came up some time ago as to allow `@container` at the top level of a context, so you could have a processor interpret a top level object as a map of graph names.

```json
{
  “@context”: {
    “@container”: [“@graph”, “@id”]
  }
}
```

**Comment by pchampin** [comment]
I like that, but would it generalize to any kind of container? If not, wouldn't it be more confusing than helpful?

**Comment by gkellogg** [comment]
Yes, it would generalize, but note that it may be more confusing than its worth, as every value which is an object would then be interpreted as a graph map, unless each term redefined it, or another context changed it.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-02-08-json-ld#section5-9).

- `RESOLVED:  Verify that @nest solution for #19 solves issue in #128 and defer until then {: #resolution14 .resolution}`
<details><summary><i class="differentiate">View the transcript</i></summary>
TriG graphs in JSON-LD<br/>
Rob Sanderson: ref: <a href="https://github.com/w3c/json-ld-syntax/issues/128">https://github.com/w3c/json-ld-syntax/issues/128</a><br/>
Gregg Kellogg: The concern is that TRiG does not use the value, insomuch as it’s just a set of graphs, names, etc, where JSON-LD has the object being the name of something in the default graph.<br/>
Ivan Herman: that’s what the issues says. What dave put in is a solution that technically works. It’s awful, and you can put in a fig leaf by aliasing @graph, but…<br/>
… what did come up is that Pierre Antoine put in a proposal for a solution and the syntax was wrong, but the way that it is now after our discussion this morning it probably works, but it is consistent.<br/>
… what he has here will work once we’ve done the cognates.<br/>
… that’s the figleaf<br/>
Gregg Kellogg: I like that more than one problem is solved with a single solution<br/>
Rob Sanderson: should we validate that it expands correctly one the fixes are in?<br/>
Gregg Kellogg: something might expand oddly…<br/>
Ivan Herman: expanding is for machines. I don’t care. But for humans, what P.A. has put in is fine.<br/>
Proposed resolution: Verify that @nest solution for #19 solves issue in #128 and defer until then (Rob Sanderson)<br/>
David Newbury: +1<br/>
Jeff Mixter: +1<br/>
Rob Sanderson: +1<br/>
Gregg Kellogg: +1<br/>
Ivan Herman: +1<br/>
Rob Sanderson: we should make sure it’s solved before closing<br/>
Harold Solbrig: +1<br/>
David I. Lehn: +1<br/>
Resolution #14: Verify that @nest solution for #19 solves issue in #128 and defer until then {: #resolution14 .resolution}<br/>
Adam Soroka: +1<br/>
</details>

**Comment by VladimirAlexiev** [comment]
Closing 141 as duplicate.
But we need a clarification in the section referenced there, a good example, and preferably a single way to do it.

**Comment by Cold-A-Muse** [comment]
Is converting TriG Graphs to JSON-LD supported? I couldn't find any documentation for this yet and ended up at this issue :sweat_smile:

**Comment by gkellogg** [comment]
JSON-LD supports conversion to and from RDF datasets, as does TriG. This is the same for all RDF formats, either converting to graphs or datasets. The Playground doesn’t directly support it (PR to do so would be great), but you can try it on my [distiller](http://rdf.greggkellogg.net/distiller).

The key is they express the same abstract data model. In the algorithm, this is described using quads, so turn TriG into quads and use as input to JSON-LD fromRdf or do the opposite.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-04-26-json-ld.html#section3-5).

- `RESOLVED:  Leave #128 open until we can determine the effects of @container / @nest`
<details><summary><i class="differentiate">View the transcript</i></summary>
TriG graphs in JSON-LD<br/>
Rob Sanderson: link: <a href="https://github.com/w3c/json-ld-syntax/issues/128">https://github.com/w3c/json-ld-syntax/issues/128</a><br/>
Simon Steyskal: [ivan contemplating about issue 128]<br/>
Ivan Herman: there was some activity on this issue in February<br/>
… there is a comment on it from pchampin providing a solution and asking whether that’s valid<br/>
… idk though<br/>
Gregg Kellogg: I think I had an action on looking into interaction with nest/container stuff<br/>
… we def. need a dedicated section on graphs/trig etc. in the bpr document<br/>
Ivan Herman: then let’s leave it open for now<br/>
Proposed resolution: Leave #128 open until we can determine the effects of @container / @nest (Rob Sanderson)<br/>
Ruben Taelman: +1<br/>
Rob Sanderson: +1<br/>
Pierre-Antoine Champin: +1<br/>
Gregg Kellogg: +1<br/>
Tim Cole: +1<br/>
Simon Steyskal: +1<br/>
Ivan Herman: +1<br/>
Dave Longley: +0<br/>
Adam Soroka: +1<br/>
David Newbury: +1<br/>
David I. Lehn: +1<br/>
Resolution #6: Leave #128 open until we can determine the effects of @container / @nest<br/>
</details>

**Comment by dlongley** [comment]
Note that https://github.com/w3c/json-ld-syntax/issues/19 may help resolve this.

**Comment by iherman** [comment]
@dlongley I am not sure I see how...

**Comment by dlongley** [comment]
@iherman,

Were you looking for something like this to resolve your issue?

```js
{
  "@context" : {
    "a": "http://example.org/a",
    "b": "http://example.org/b",
    "c":  "http://example.org/c",
    "b:predicate" : { "@type" : "@id" }
  },
  "@included": [{
    "@id" : "http://example.org/gr1",
    "@graph" : {
      "@id" : "a:something",
      "a:predicate" : "value1",
      "b:predicate" : "c:something1"
    }
  }, {
    "@id" : "http://example.org/gr2",
    "@graph" : {
      "@id" : "a:something",
      "a:predicate" : "value2",
      "b:predicate" : "c:something2"
    }
  }]
}
```

Supposing, of course, that the above resolves to the same quads as the TriG.

**Comment by VladimirAlexiev** [comment]
> either converting to graphs or datasets

@gkellogg a stupid question: could you explain the difference?

**Comment by gkellogg** [comment]
As with other dataset formats, such as TriG, you may not actually use named graphs, in chich case the JSON-LD is used as a graph format. If you use it to describe datasets, it’s a dataset format. TriG is the same, as it’s a superset of Turtle.

The new included feature, as @dlongley shows, can make it easier to express datasets sharing a common context.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-08-02-json-ld#section4-2).

- `RESOLVED:  close 108 with statement that potentially related SRI issues will be closed as differed`
- `RESOLVED:  close 128`
<details><summary><i class="differentiate">View the transcript</i></summary>
Confirm state of <code>@import</code> usage<br/>
Benjamin Young: -> <a href="https://github.com/w3c/json-ld-syntax/issues/108">https://github.com/w3c/json-ld-syntax/issues/108</a> Issue 108<br/>
Benjamin Young: Request by Rob to state to ourselves to not quickly add more features to <code>@import.</code><br/>
Ivan Herman: +1<br/>
Benjamin Young: This import issue is closable, as it is in the spec<br/>
Gregg Kellogg: +1<br/>
Gregg Kellogg: This also puts the nail in for SRI?<br/>
Benjamin Young: Yes<br/>
… We would defer and close the SRI issue<br/>
Proposed resolution: close 108 with statement that potentially related SRI issues will be closed as differed (Benjamin Young)<br/>
Ivan Herman: +1<br/>
Gregg Kellogg: Can we close the issue on trig graphs?<br/>
Ruben Taelman: +1<br/>
Benjamin Young: +1<br/>
Tim Cole: +1<br/>
Gregg Kellogg: +1<br/>
Resolution #4: close 108 with statement that potentially related SRI issues will be closed as differed<br/>
Proposed resolution: close 128 (Ivan Herman)<br/>
Tim Cole: +1<br/>
Ruben Taelman: +1<br/>
Ivan Herman: +1<br/>
Benjamin Young: +1<br/>
Gregg Kellogg: +1<br/>
Resolution #5: close 128<br/>
</details>
