### ISSUE TITLE
Allow @value, @language and @type simultaneously

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-syntax#13]
It is currently not possible to have all three of `@value`, `@language` and `@type`.  Meaning that for text with embedded mark up, it is impossible to have both language and format (the datatype given in `@type`) ... neither of which can be reliably introspected from the value.

Any time there is markdown, html, xml, json, yaml, latex, or any other formatting instructions beyond simply print the string to the user, this becomes extremely valuable. Given the usage of those formats on the web, it would enable appropriate management of internationalized texts.

Example:
```
{
  "description": {
    "@value":"<p>Some <b>description</b></p>",
    "@type": "rdf:XMLLiteral",
    "@language" : "en-latn"
  }
}
```

Reference: https://lists.w3.org/Archives/Public/public-linked-json/2014Aug/0031.html
Door-Opened-By: https://github.com/json-ld/json-ld.org/issues/583

Original issue: [Allow @value, @language and @type simultaneously #585](https://github.com/json-ld/json-ld.org/issues/585)

**Comment by azaroth42** [comment]
This is now Door-Opened-By #11, and they should be discussed together, after the general principle of whether RDF is the data model or not.

**Comment by azaroth42** [comment]
Closing, wontfix, as new features should be compatible with the RDF data model.
WG Resolution: https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-08-03-json-ld#section2-3
