### ISSUE TITLE
json-ld 1.1: @vocab gets ignored in nested @context with @id-typed values

### ISSUE THREAD

**Issue by lukasheinrich** [w3c/json-ld-syntax#138]
(originally opened in https://github.com/json-ld/json-ld.org/issues/689 but realized it was the wrong repo)

on the dev playground, specifying a nested context for the expansion of a object of type "@id" correctly expands a namespace defined in the nested context

```
{
  "@context": {
    "@vocab": "http://myvobab/",
    "@version": 1.1,
    "pred": {
      "@id": "http://a/predicate",
      "@type": "@id",
      "@context": {
        "mv": "http://myvobab/"
      }
    }
  },
  "pred": "mv:identifier",
  "name": "identifier"
}
```

expands to 

```
[
  {
    "http://myvobab/name": [
      {
        "@value": "identifier"
      }
    ],
    "http://a/predicate": [
      {
        "@id": "http://myvobab/identifier"
      }
    ]
  }
]
```

but when using `@vocab` it does not work:

```
{
  "@context": {
    "@vocab": "http://myvobab/",
    "@version": 1.1,
    "pred": {
      "@id": "http://a/predicate",
      "@type": "@id",
      "@context": {
        "@vocab": "http://myvobab/"
      }
    }
  },
  "pred": "identifier",
  "name": "identifier"
}
```

expands to 

```
[
  {
    "http://myvobab/name": [
      {
        "@value": "identifier"
      }
    ],
    "http://a/predicate": [
      {
        "@id": "https://json-ld.org/playground-dev/identifier"
      }
    ]
  }
]
```

is this expected behavior? I would have expected both documents to expand in the same manner

**Comment by gkellogg** [comment]
JSON-LD considers most values that are IRIs to be _document relative_, while properties and values of `@type` are _vocabulary relative_. When you specify `"pred": "identifier"` "identifier" is considered to be _document relative_, as `pred` is defined using `"@type": "@id"`. When you use the "mv:identifier" form, it is a _compact IRI_, not a _relative IRI_, so it is turned into an _absolute IRI_ using the value of the "mv" term.

If you want values of `pred` to be considered as _vocabulary relative_ IRIs, you would use `"@type": "@vocab"` in the term definition.

**Comment by lukasheinrich** [comment]
thanks -- that was exactly what I needed -- closing.
