### ISSUE TITLE
"Lax” IRIs

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-syntax#14]
Allows arbitrary strings to be used as IRIs

Original issue: ["Lax" IRIs #590](https://github.com/json-ld/json-ld.org/issues/590)

**Comment by BigBlueHat** [comment]
Also, it's also essentially already covered (conceptually) by the options for minting one's own IRI's. The content proposed in the original issue would simply become an ad-hoc URN of some kind. So, I don't believe there's anything here that's actually "fixable" because it isn't actually broken. 😃

**Comment by azaroth42** [comment]
+1 to closing.

**Comment by azaroth42** [comment]
Closing wontfix. Rationale: Isn't part of the RDF data model, and does not add value.

WG Resolution: https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-07-27-json-ld#section2-2
