### ISSUE TITLE
can jsonld express multiple top-level graphs?

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c/json-ld-syntax#141]
https://w3c.github.io/json-ld-syntax/#example-90-identifying-and-making-statements-about-a-graph
"When a JSON-LD document's top-level structure is an dictionary that contains no other keys than `@graph` and optionally `@context`, `@graph` is considered to express the otherwise implicit default graph."

It would seem to the uninitiated that JSONLD cannot express multiple named graphs at the top level in the same payload 
- later examples produce multiple *anonymous* graphs
- https://w3c.github.io/json-ld-syntax/#example-96-referencing-named-graphs-using-an-id-map shows multiple named graphs, but they are attached as objects of a particular property:

```ttl
#<http://example.org/foaf-graph>
#  <http://example.org/graphMap>
#    <http://manu.sporny.org/about#manu>,
#    <http://greggkellogg.net/foaf#me>;
#  prov:generatedAtTime "2012-04-09"^^xsd:date .

<http://greggkellogg.net/foaf#me> {
  <http://greggkellogg.net/foaf#me> a foaf:Person;
     foaf:knows <http://manu.sporny.org/about#manu>;
     foaf:name "Gregg Kellogg" .
}

<http://manu.sporny.org/about#manu> {
  <http://manu.sporny.org/about#manu> a foaf:Person;
     foaf:knows <http://greggkellogg.net/foaf#me>;
     foaf:name "Manu Sporny" .
}
```

Can I express the turtle above, but without the commented-out part?

**Comment by iherman** [comment]
I think this is covered by #128. "Covered" means that it has been discussed, and some changes on the document may come to make this a bit easier.

If you agree with this, can you close this issue (and follow #128)?

**Comment by VladimirAlexiev** [comment]
Agreed
