### ISSUE TITLE
typo (?) in section 9 intro - https://w3c.github.io/json-ld-syntax/#json-ld-grammar

### ISSUE THREAD

**Issue by rdewaele** [w3c/json-ld-syntax#146]
https://w3c.github.io/json-ld-syntax/#json-ld-grammar

The subject sentence currently states:
> A JSON-LD document MUST be a single node object, a dictionary consisting of only the members @context and/or @graph, or an array or zero or more node objects.

I believe what is meant is (strikethrough / bold):
> A JSON-LD document MUST be a single node object, a dictionary consisting of only the members @context and/or @graph, or an array ~or~ **of** zero or more node objects.

If my interpretation / suggestion is incorrect, I would like to propose adding an Oxford comma. However, this would still confuse me as that would not seem to imply valid JSON syntax.

**Comment by pchampin** [comment]
Well spotted, thanks.
