### ISSUE TITLE
DocumentLoader should be more visible in the specs

### ISSUE THREAD

**Issue by azaroth42** [w3c/json-ld-syntax#149]
Many issues around resolution of contexts come down to a lack of understanding about the use of the documentLoader.  These questions might not come up as often if documentloader was more visible in the specifications, including in the syntax document even though it's an API feature.

The issue is editorial to try to explain why network/resolution related issues are the concern of the document loader. Related to #148, but not necessarily to security directly.

**Comment by gkellogg** [comment]
PR #196 reviewed by @pchampin. Closing.
