### ISSUE TITLE
Using explicit @prefix declaration to create compact IRIs

### ISSUE THREAD

**Issue by rubensworks** [w3c/json-ld-syntax#151]
This issue is regarding one of the new [examples](https://w3c.github.io/json-ld-syntax/#example-32-using-explicit-prefix-declaration-to-create-compact-iris) regarding term expansion where the term definition ends in a non-gen-delim character:

```json
{
  "@context": {
    "compact-iris": {"@id": "http://example.com/compact-iris-", "@prefix": true},
    "property": "http://example.com/property"
  },
  "property": {
    "@id": "compact-iris:are-considered",
    "property": "@prefix does not require a gen-delim"
  }
}
```

If I understand the JSON-LD 1.1 versioning mechanic correctly,
this should be tagged with `"@version": 1.1` to avoid that 1.0 processors handle this inconsistently.

As such, am I correct to assume that this example should be changed to the following?:

```json
{
  "@context": {
    "@version": 1.1,
    "compact-iris": {"@id": "http://example.com/compact-iris-", "@prefix": true},
    "property": "http://example.com/property"
  },
  "property": {
    "@id": "compact-iris:are-considered",
    "property": "@prefix does not require a gen-delim"
  }
}
```

If so, I can send in a PR for this.

**Comment by gkellogg** [comment]
Yes, it should use `@version`, but I’d like to see why it’s not found in Travis tests first. All examples are run using a script, that is intended to find such errors.

**Comment by gkellogg** [comment]
It ends up, we weren't running examples using validation mode, so the lack of `@version` wasn't caught. We were also not processing HTML quite right, which goes back before there was support for HTML content in the Ruby implementation. Both fixed now, thanks for noticing!
