### ISSUE TITLE
Consistent use of Dublin Core prefixes

### ISSUE THREAD

**Issue by pchampin** [w3c/json-ld-syntax#159]
In all examples using the Dublin Core vocabulary, the prefix is declared:
```json
"dc": "http://purl.org/dc/terms/",
```

while, in the [recommended context](https://github.com/w3c/json-ld-rc/blob/master/context.jsonld),
the following prefixes are defined:
```json
"dc": "http://purl.org/dc/elements/1.1/",
"dc11": "http://purl.org/dc/elements/1.1/",
"dct": "http://purl.org/dc/terms/",
"dcterms": "http://purl.org/dc/terms/",
```

I suggest we align with the recommended context, for example by replacing prefix `dc` with `dct` in the examples of the Syntax document.

**Comment by azaroth42** [comment]
Propose that this is editorial, doesn't need discussion on a call.

**Comment by gkellogg** [comment]
RDFa used “dc” for DC Terms, which was probably not a great idea in retrospect. I’d favor settling on dc11 and dct.

**Comment by iherman** [comment]
I have seen `dct` or `dcterms` a lot, not much `dc11`. I would opt for `dct`.

**Comment by gkellogg** [comment]
I see you changed the “dc” term in the JSON-LD recommended context from terms to elements. I think there is a danger that our using “dc” for elements could be confusing because of this history. I’ve also seen “dce” used for elements.

**Comment by iherman** [comment]
The reason I changed `dc` was because [the schema.org context file](https://schema.org/docs/jsonldcontext.json) has

```json
"dc": "http://purl.org/dc/elements/1.1/",
"dcterms": "http://purl.org/dc/terms"
```

I thought it is important to be in line with schema.org; lots of people may use these two already this way. I have added

```json
"dct" : "http://purl.org/dc/terms",
"dc11": "http://purl.org/dc/elements/1.1/"
```

because I saw them somewhere else.

Unless this really creates problems, I would propose we would align ourselves on the schema.org usage.

**Comment by azaroth42** [comment]
We (annos, and elsewhere, see below) have also used "dc" for elements and "dcterms" for terms.  I don't like "dct" as there's also a Dublin Core Types ontology.

See: 
 * https://www.w3.org/ns/anno.jsonld
 * https://iiif.io/api/presentation/2/context.json
 * https://linked.art/ns/v1/linked-art.json

**Comment by pchampin** [comment]
Looking good in the spec texts now. However, I just noticed that the "Library" example in the playground uses the `dcterms` for `http://purl.org/dc/elements/1.1/`... @davidlehn 
Sorry, but I couldn't find any repo specific to the playground to file this issue.

**Comment by gkellogg** [comment]
I must have broken that, it’s in github.com/json-ld/json-ld.org.

**Comment by gkellogg** [comment]
Fixed in https://github.com/json-ld/json-ld.org/commit/2d0e5371f531d22d962a7ff6c02a3a1339c601b9.
