### ISSUE TITLE
Cyclic definitions in section 9

### ISSUE THREAD

**Issue by pchampin** [w3c/json-ld-syntax#160]
Section 9.2 defines a node object with a set of conditions, one of them being "it is not a graph object".

Section 9.4 defines a graph object with a set of conditions, one of them being "it is not a node object".

This cyclic definition is a problem for normative text. Furthermore, the later does not say that a graph object MUST contain a `@graph` member (or an alias of that keyword)! Which it must, right?

Suggestion: replace in 9.4 "it is not a node object" by "it contains a `@graph` member (or an alias of that keyword)".

**Comment by gkellogg** [comment]
Note that node objects may contain `@graph`. Really graph objects purely define named graphs, either with an explicit id, or implicit. If properties are defined on the graph name, it’s a node object.  This is, of course, pretty messy, as it evolved over time, particularly with graph containers and maps. We should focus on cleaning up such nomenclature.

**Comment by azaroth42** [comment]
Seems like editorial work only? Or need to discuss on a call?
