### ISSUE TITLE
Missing @type in expanded form when an id map is used in conjunction with @type in a term definition

### ISSUE THREAD

**Issue by keyvan-m-sadeghi** [w3c/json-ld-syntax#165]
Building on [the example from the specs](https://w3c.github.io/json-ld-syntax/#example-83-indexing-data-in-json-ld-by-node-identifiers) with 3 changes marked by `// Here!`:

```javascript
{
  "@context": {
    "@version": 1.1,
    "schema": "http://schema.org/",
    "name": "schema:name",
    "body": "schema:articleBody",
    "words": "schema:wordCount",
    "post": {
      "@id": "schema:blogPost",
      "@container": "@id",
      "@type": "schema:BlogPosting" // Here!
    }
  },
  "@id": "http://example.com/",
  "@type": "schema:Blog",
  "name": "World Financial News",
  "post": {
    "http://example.com/posts/1/en": {
      "body": "World commodities were up today with heavy trading of crude oil...",
      "words": 1539
    },
    "http://example.com/posts/1/de": {
      "body": "Die Werte an Warenbörsen stiegen im Sog eines starken Handels von Rohöl...",
      "@type": "schema:BlogPosting",  // Here!
      "words": 1204
    },
    "http://example.com/posts/2/en": "hello" // Here!
  }
}
```

[Open in playground](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22%40version%22%3A1.1%2C%22schema%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22name%22%3A%22schema%3Aname%22%2C%22body%22%3A%22schema%3AarticleBody%22%2C%22words%22%3A%22schema%3AwordCount%22%2C%22post%22%3A%7B%22%40id%22%3A%22schema%3AblogPost%22%2C%22%40container%22%3A%22%40id%22%2C%22%40type%22%3A%22schema%3ABlogPosting%22%7D%7D%2C%22%40id%22%3A%22http%3A%2F%2Fexample.com%2F%22%2C%22%40type%22%3A%22schema%3ABlog%22%2C%22name%22%3A%22World%20Financial%20News%22%2C%22post%22%3A%7B%22http%3A%2F%2Fexample.com%2Fposts%2F1%2Fen%22%3A%7B%22body%22%3A%22World%20commodities%20were%20up%20today%20with%20heavy%20trading%20of%20crude%20oil...%22%2C%22words%22%3A1539%7D%2C%22http%3A%2F%2Fexample.com%2Fposts%2F1%2Fde%22%3A%7B%22body%22%3A%22Die%20Werte%20an%20Warenb%C3%B6rsen%20stiegen%20im%20Sog%20eines%20starken%20Handels%20von%20Roh%C3%B6l...%22%2C%22%40type%22%3A%22schema%3ABlogPosting%22%2C%22words%22%3A1204%7D%2C%22http%3A%2F%2Fexample.com%2Fposts%2F2%2Fen%22%3A%22hello%22%7D%7D)

The expanded form includes the `@type` for the simple key-value pair `"http://example.com/posts/2/en": "hello"`, but not for `"http://example.com/posts/1/en"`:

```javascript
[
  {
    "@id": "http://example.com/",
    "@type": [
      "http://schema.org/Blog"
    ],
    "http://schema.org/name": [
      {
        "@value": "World Financial News"
      }
    ],
    "http://schema.org/blogPost": [
      {
        "@type": [
          "http://schema.org/BlogPosting"  // Here!
        ],
        "http://schema.org/articleBody": [
          {
            "@value": "Die Werte an Warenbörsen stiegen im Sog eines starken Handels von Rohöl..."
          }
        ],
        "http://schema.org/wordCount": [
          {
            "@value": 1204
          }
        ],
        "@id": "http://example.com/posts/1/de"
      },
      {
        "http://schema.org/articleBody": [
          {
            "@value": "World commodities were up today with heavy trading of crude oil..."
          }
        ],
        "http://schema.org/wordCount": [
          {
            "@value": 1539
          }
        ],
        "@id": "http://example.com/posts/1/en"  // Not Here!
      },
      {
        "@type": "http://schema.org/BlogPosting",  // Here!
        "@value": "hello",
        "@id": "http://example.com/posts/2/en"
      }
    ]
  }
]
```

`@type` is manually added for `"http://example.com/posts/1/de"` for the sake of comparison, which produces the expected result IMHO.

Is this my wrong understanding or is it missing from the expansion algorithm?

Thanks in advance.

**Comment by azaroth42** [comment]
Yup, this is a common misunderstanding unfortunately. One that I have had in the past from reading the specs!  You can't add an `@type` value into a context where the type is a class, and thus have the class added to the triples. That level of transformation of content is outside of the scope of JSON-LD in its currently chartered work.

See also: https://github.com/w3c/json-ld-syntax/issues/76 

Thanks!

**Comment by keyvan-m-sadeghi** [comment]
Makes perfect sense. Thanks @azaroth42
