### ISSUE TITLE
Feedback: My Adventure In JSON-LD: Understanding @context Semantics

### ISSUE THREAD

**Issue by cjslep** [w3c/json-ld-syntax#169]
For go-fed/activity's `astool` (ActivityStreams tool, ActivityStreams is a JSON-LD vocabulary) it processes JSON-LD `@context` definitions in order to generate code that represents native types in Golang (along with all the serialization and deserialization code).

After much discussion in an [issue there](https://github.com/w3c/activitystreams/issues/500), I've come to the personal conclusion that the existing [Context Processing algorithms](https://www.w3.org/TR/json-ld-api/#context-processing-algorithm) are inadequate for doing this level of understanding a `@context` document. It is, however, sufficient for the class of algorithms I colloquially call "text transformations" (expansion, compaction, normalization).

To go beyond just these textual transformations requires the processor knowing which IRI nodes represent entire further `@context` vocabularies to process and which IRIs are "leaf nodes" -- ones that actually represent a type. Current JSON-LD descriptions are insufficient and so go-fed `astool` tends to rely on careful convention.

Furthermore, certain JSON-LD documents that are valid for text transformations introduce problems for semantic understanding. For example, ActivityStreams defines itself with a prefix within its own `@context` document which requires special care by a semantic understanding processor so that it is NOT to be recursively traversed (because the IRI Expansion algorithm is generally modified to recurse in this case, unlike the unmodified version).

The ultimate goal of a semantic understanding processor is to be able to identify and traverse IRIs that represent items requiring further understanding, and identifying but not traversing items that are types and can build cross-`@context` references between them. My particular use case for this reference graph was to automatically generate native Golang types.

I don't really want to get involved in the JSON-LD 1.1 changes. Nor am I making concrete suggestions. I just wanted to make my voice heard for the record.

**Comment by BigBlueHat** [comment]
@cjslep it seems you got your answers in https://github.com/w3c/activitystreams/issues/500#issuecomment-488095045 and https://github.com/w3c/activitystreams/issues/500#issuecomment-489346727

The context processing algorithms result in IRIs (which may or may not be URLs)--i.e. they don't necessarily "locate" anything...they only identify). Essentially, the `@context` object is about mapping in-document terminology to global-world terminology...no more, no less.

If you need more complete vocabulary and ontology definitions, then [OWL](https://www.w3.org/TR/owl-syntax/) documents may provide what you want and/or [JSON Schema](https://json-schema.org/). Schema.org publishes [their ontology in OWL](https://github.com/schemaorg/schemaorg/blob/master/docs/schemaorg.owl) for example.

Lastly, Google's [Structured Data Testing Tool](https://search.google.com/structured-data/testing-tool) is currently limited by only processing `"@context": "http://schema.org"` definitions. Consequently, the [JSON-LD Playground](https://json-ld.org/playground/) would be a better testing tool for general JSON-LD needs and usage.

If you believe there's more we can clarify in either the [Syntax](https://w3c.github.io/json-ld-syntax/) or [API](https://w3c.github.io/json-ld-api/) documents, feel free to re-open this issue with requests.

Thanks!
🎩 
Co-Chair, JSON-LD WG
