### ISSUE TITLE
Consider the inverse of @container:@set? 

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-syntax#17]
We should consider whether or not the opposite of `@container:@set` is sufficiently valuable to include. This would be when there is exactly one entry in an `@list`, instead of compacting to an array, compact to a single item. 

It is valid as input already (http://tinyurl.com/yccbfl9j) but compaction will always create the JSON array.

The context might say:

```
{
  "listy": {"@id": "eg:steps", "@container": ["@list", "@single-item-is-value"]}
}
```

For example, the schema.org `recipeInstructions` for a single step could just be a string, not an array containing a string.  Such as this very simple guacamole https://www.allrecipes.com/recipe/14231/guacamole/ could be compacted to:

```
"recipeInstructions": "In a medium bowl, mash together the avocados, lime juice, ..."
```
even if `recipeInstructions` was an `@list`.

(/ht @danbri)

Original issue: [Consider the inverse of @container:@set? #646](https://github.com/json-ld/json-ld.org/issues/646)

**Comment by azaroth42** [comment]
I don't personally have this use case, but I support its inclusion. Control over the shape of the JSON result is the goal, and this is a particular structure that otherwise cannot be generated.

**Comment by gkellogg** [comment]
The implication would be that, when expanding, those single values would be treated as list entries as well, which is just what the current algorithm does.

If the default for compaction was otherwise, we could consider `"@container": ["@list", "@set"]` as a way of always compacting to the array form, and default to the non-array form for single items. We could potentially consider this for `@version: 1.1` behavior, if we don't consider this an incompatibility. Currently, that combination is illegal. This is generally how `@set` is used for other container types and would be the principle of least surprise.

**Comment by simonstey** [comment]
> The implication would be that, when expanding, those single values would be treated as list entries as well, which is just what the current algorithm does. If the default for compaction was otherwise, we could consider `"@container": ["@list", "@set"]` as a way of always compacting to the array form, and default to the non-array form for single items.

assuming that we would adopt the non-array form for single item `@list`, the fictious `"@container": ["@language", "@list"]` would basically be equivalent to `"@container": "@language"` (if the former was permitted by the spec) right?

On a side note, I wonder how such a change would affect the following rationale given in [9.5 Lists and Sets:](https://w3c.github.io/json-ld-syntax/#lists-and-sets)
> Values of terms associated with an `@set` or `@list` container will always be represented in the form of an array when a document is processed—even if there is just a single value that would otherwise be optimized to a non-array form in compact document form. **This simplifies post-processing of the data as the data is always in a deterministic form.**

**Comment by azaroth42** [comment]
[Resolution of the WG](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-09-14-json-ld#resolution3) on the call on 2018-09-14 was to close this issue, won't fix but without prejudice. There are no use cases known for the compaction side, and the expansion of that data to RDF works as expected already.  If use cases are brought to the WG, then we will re-open the issue and consider them.
