### ISSUE TITLE
Example editorial / styling issues in syntax

### ISSUE THREAD

**Issue by azaroth42** [w3c/json-ld-syntax#178]
- [ ] Example 4 has an errant "Context" appearing on the right hand side.

![Screen Shot 2019-05-14 at 11 49 10 AM](https://user-images.githubusercontent.com/871868/57723891-80a72b80-763e-11e9-8163-8d5e601629ef.png)

- [ ] Not all examples of instance data have the tabs for expanded form (etc), e.g. Example 26 does not have them, but 27 immediately following does.

![Screen Shot 2019-05-14 at 11 51 33 AM](https://user-images.githubusercontent.com/871868/57723986-acc2ac80-763e-11e9-988d-7b30a13a9b85.png)

/ht @kasei

**Comment by gkellogg** [comment]
In some cases the example is used as a reference for others which have tabs to show expansion and so forth, so it doesn’t always make sense to have tabs.

**Comment by gkellogg** [comment]
In example 4, the “Context” isn’t errant, it’s there to show that this is a context documentment, Wichita used elsewhere. This is more prevalent in the api and framing docs. It’s controlled by having an example with class “contex”.

**Comment by davidlehn** [comment]
I also think that "Context" and "Input" styled offset text looks out-of-place and more like a mistake.  It helps a bit to make it stand out as a label with something like `border: solid thin black; padding: 0.5em`.

**Comment by davidlehn** [comment]
That example 26/27 is also a bit odd since a reader probably doesn't want to open the expanded output as playground input.  They'd be more interested in opening Ex 26 and seeing the expanded output.

**Comment by gkellogg** [comment]
There was an issue of properly identifying examples which showed something other than compacted JSON-LD. This was my attempt to address that. Note that structurally, it’s simply a css class and the “Context” is implemented entirely in css. Someone that has a better idea of how such things should be represented should suggest an update to the css that clarifies the intention.

Sometimes it makes sense for the playground to show the result of expanding the input, others the result of compacting using a context or framing using a frame.
