### ISSUE TITLE
Syntax examples missing the result of compaction

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-syntax#179]
The paragraph just above [example 77](https://w3c.github.io/json-ld-syntax/#example-77-defining-property-nesting) talks about what happens during compaction (in this case, nesting), but the example does not show results of that compaction process. (This happens repeatedly, including examples 86, 89, and 92.)

> Similarly, term definitions may contain a @nest property referencing a term aliased to @nest which will cause such properties to be nested under that aliased term when compacting. In the example below, both main_label and other_label are defined with "@nest": "labels", which will cause them to be *serialized under labels when compacting*.

(emphasis added)

**Comment by azaroth42** [comment]
Or indeed that the results are in the "original" tab, which gives the impression that it is the input to the compaction process, rather than the output.

Suggest renaming "Original" to "Compacted" throughout
