### ISSUE TITLE
Should examples use IRIs in the foaf vocabulary that do not exist?

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-syntax#180]
[Example 110](https://w3c.github.io/json-ld-syntax/#example-110-compacting-using-a-default-vocabulary) in the syntax document includes a `foaf:Restaurant` IRI that does not actually exist in the foaf vocabulary. Should this example use schema.org instead?

**Comment by gkellogg** [comment]
That’s a bug. I need to do more validation that vocabulary items used are defined in CI.
