### ISSUE TITLE
Consider Infra spec for describing primitive types

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-syntax#199]
@marcoscaceres pointed out the [Infra Spec](https://infra.spec.whatwg.org) (another What WG product) that exists as a way of describing some fundamental types, such as those we use. Currently, we use a combination of ECMASCRIPT and WebIDL to describe things like strings, numbers, booleans, and objects/dictionaries, which isn't entirely satisfying. Infra might be a better way to go, but would likely require some large changes to the text.

In 1.1 we (I) made a change from describing changes to objects to dictionaries, because JSON objects are serialization artifacts of an internal structure and it doesn't make sense to describe updating them. Also, we were trying to abstract away from JSON for describing API operations.

We're currently updating our terminology (see PR #198) and now might be a time to consider such a change.

Other than changing definition references, Infra uses the concept of a [Set](https://infra.spec.whatwg.org/#sets) and [Map](https://infra.spec.whatwg.org/#maps) (with [entries](https://infra.spec.whatwg.org/#map-entry))  in deference to our [array](https://www.w3.org/TR/json-ld11/#dfn-array) and [dictionary](https://heycam.github.io/webidl/#dfn-dictionary) (with [members](https://heycam.github.io/webidl/#dfn-dictionary-member)).

**Comment by iherman** [comment]
I had a cursory look at that document and it mostly looks to me as a stylistic agreement (ie, not some sort of a replacement of WebIDL). Which is perfectly fine, of course, but then whether it is appropriate for our spec or not is entirely an editorial issue. Ie, @gkellogg and @pchampin have, as far as I am concerned, full decision power on this...

**Comment by dlongley** [comment]
Looking at this... I had an initial concern with how using this other spec's language would be understood in the context of JSON and JavaScript's `parse` and `stringify` methods. For example, I wouldn't want an implementer to think "Wait, I can't just call `JSON.parse()` ... I have to translate the output to `Set` and `Map` types in my implementation?" However, it seems that the Infra spec has a section that is explicitly about this -- and it seems to assuage some concern that this is just about being able to describe types in standards independent of realm:

https://infra.spec.whatwg.org/#json

> The above two operations operate on JavaScript values directly; in particular, this means that the involved objects or arrays are tied to a particular JavaScript realm. In standards, it is often more convenient to parse JSON into realm-independent maps, lists, strings, booleans, numbers, and nulls.

This makes me more comfortable that there wouldn't be some kind of impedance mismatch or confusion with how implementations work with parsing/serializing JSON and the Infra types.

**Comment by gkellogg** [comment]
Actually, we'll want to use [List](https://infra.spec.whatwg.org/#list) instead of [Set](https://infra.spec.whatwg.org/#sets). This implies updating the language where we use _array_ to using _list_ as well as updating _dictionary_ to _map_.

**Comment by gkellogg** [comment]
Included changes for this in PR #198.

**Comment by gkellogg** [comment]
Closed via #198, w3c/json-ld-api#116, and https://github.com/w3c/json-ld-framing/commit/ba733715bf92f1498020b20ddc166ad63c23a5f7
