### ISSUE TITLE
Normativeness of the embedded form of JSON-LD

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-syntax#22]
Section [4.28](https://w3c.github.io/json-ld-syntax/#embedding-json-ld-in-html-documents) of the draft defines JSON-LD embedded in HTML via the `script` tag. However, the section is marked as 'non-normative'.

In view of the importance of that format (e.g., this is the main format accepted by schema.org processors these days) we should consider giving it a normative status.

**Comment by iherman** [comment]
Not really. Except that #57 says

> We've discussed making this normative, requiring JSON-LD processors to be able to identify and extract JSON-LD from a script tag with type application/ld+json within the HTML document.

Ie, it discusses details to be decided upon _provided_ this issue is accepted, ie, there is a resolution to turn that section in normative.

Maybe voting on this could be done by email, we can then close it and concentrate on #57 if the decision is a 'yes'.

**Comment by gkellogg** [comment]
> Is there a difference between this issue and #57?

Not really, my mistake for duplicating.

**Comment by gkellogg** [comment]
Agree we can close this, and then work on the details in #57, and we may need to break out the different points into separate issues.

**Comment by azaroth42** [comment]
:+1: Closing, duplicate.
