### ISSUE TITLE
Data Model Overview is misleading?

### ISSUE THREAD

**Issue by azaroth42** [w3c/json-ld-syntax#225]
> The graph contains nodes, which are connected by directed-arcs. A node is typically data such as a string, number, typed values (like dates and times) or an IRI.

Propose to use the more common "edges" rather than "arcs" and to remove the hyphen.  Also, that the IRI is a different node than the resource itself ... an IRI is the value of `@id`, whereas a JSON object representing a resource is (IMO) the most common node in the graph.

Propose:

> The graph contains nodes, which are connected by directed edges. A node is either a resource with properties, or the data values of those properties including strings, numbers, typed values (like dates and times) and IRIs.

**Comment by gkellogg** [comment]
RDF Concepts calls them args: "An RDF graph can be visualized as a node and directed-arc diagram, in which each triple is represented as a node-arc-node link".

This text is essentially right out of RDF Concepts. Edges may be more common, but we use the RDF data model, and this is where it's defined.

Also, RDF Concepts does not really distinguish between an IRI and the node that it labels. But, I think we can use most of what you suggest by keeping "directed-arc".

> The graph contains nodes, which are connected by _directed-arcs_. A node is either a resource with properties, or the data values of those properties including strings, numbers, typed values (like dates and times) and IRIs.

**Comment by azaroth42** [comment]
:+1: Works for me
