### ISSUE TITLE
IRI-s vs. URL-s

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-syntax#25]
Wonder whether we should not adopt URL-s in the terminology, with the remark that the term encompasses IRI-s like done, eg, in the [HTML document reference](https://www.w3.org/TR/html5/references.html#normative). This is where developers have gone, and it may be silly to ignore it and continue using the IRI term...

(The same comment applies to the other two documents, too, obviously.)

**Comment by gkellogg** [comment]
It seems to be the way things are going, although I personally miss the distinction between “Identifier” and “Locator”, which implies dereferencability.

**Comment by gkellogg** [comment]
Interesting that DOM continues to use URI, at least for [baseURI](https://dom.spec.whatwg.org/#dom-node-baseuri). RDF 1.1 uses IRI, so it may make sense to continue that usage.

**Comment by iherman** [comment]
I see end users the main targets of this document, which intends to be very didactic (which is good!). Application developers (who would use the DOM) is not really our concern in this respect (besides, baseURI is probably kept for backward compatibility reasons).

Yes, RDF uses IRI, we cannot change that. And it is probably the precise way of saying things. But I do not consider this as a decisive factor...

**Comment by azaroth42** [comment]
PROPOSAL: Defer any change until the extent to which technical differences between URL and IRI can be determined, especially any difference between web browser and other stacks.

**Comment by azaroth42** [comment]
Proposal above was [accepted by the WG](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-09-14-json-ld#resolution2), on the call on 2018-09-14. Tagging defer until the above is satisfied.

**Comment by krobi64** [comment]
Question around this topic: Until we can implement a `did` method for our framework (https://po.et), I was looking to use https://tools.ietf.org/html/rfc2397 as a way to for our users to anonymously insert identity, specifically for the Ed25519 2018 Signature Verification Key. It seems that you are specifically referencing `https` and `http` URL schemes. That is far too limiting.

**Comment by BigBlueHat** [comment]
@krobi64 that's precisely why many of us would prefer to *keep* the IRI terminology in use in the spec now: https://www.w3.org/TR/json-ld11/#iris

By that definition `data:` IRIs/URLs work just fine. Their a bit unusual as standalone identifiers (due to how long they can get), but they certainly work fine as values.

JSON-LD supports *any* kind of IRI (including URIs, URNs, and URLs) not just `https` and `http` URL schemas (however common those might be).

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-02-08-json-ld#section5-4).

- `RESOLVED:  Close syntax #25 wontfix, we stick with IRI rather than using URL {: #resolution9 .resolution}`
<details><summary><i class="differentiate">View the transcript</i></summary>
URL-s vs. IRI-s<br/>
Ivan Herman: <a href="https://github.com/w3c/json-ld-syntax/issues/25">https://github.com/w3c/json-ld-syntax/issues/25</a><br/>
Proposed resolution: Close syntax #25 wontfix, we stick with IRI rather than using URL (Rob Sanderson)<br/>
Gregg Kellogg: +1<br/>
Adam Soroka: +1<br/>
Rob Sanderson: +1<br/>
Ivan Herman: +1<br/>
Harold Solbrig: +1<br/>
David Newbury: +1<br/>
Simon Steyskal: +1<br/>
Benjamin Young: +1<br/>
Jeff Mixter: +1<br/>
Resolution #9: Close syntax #25 wontfix, we stick with IRI rather than using URL {: #resolution9 .resolution}<br/>
</details>
