### ISSUE TITLE
Describe scoped context with @base for id map?

### ISSUE THREAD

**Issue by azaroth42** [w3c/json-ld-syntax#254]
Adding `@base` as a scoped context below an id map makes the structure much more useful:

```
    "post": {
      "@id": "schema:blogPost",
      "@container": "@id",
      "@context": {
        "@base": "http://content.com/posts/"
      }
    }
```

As then the URIs become relative to base, and can thus be simple keys / slugs.

**Comment by gkellogg** [comment]
Irrelevant with changes to tests in #253.

**Comment by azaroth42** [comment]
Irrelevant as in no longer works? (And if so ... wouldn't that be a normative change?)
Or irrelevant as in this could be a best practice, but not needed in the spec?

**Comment by gkellogg** [comment]
No, it's relevant.

**Comment by gkellogg** [comment]
It might be considered a bug, but the algorithm doesn't set the local context when processing id-map keys, it is deferred until processing values, thus your example won't work.

We could (probably should) add a step after 13.8.3.1 to set _map context_ if `@container` includes `@id`; I'm not sure why we didn't do this.

This will require more tests for this.

In the mean time, I'm just going to update the example to set `@base` in the top-level context.

**Comment by azaroth42** [comment]
Hmm, then I'm doubly glad I found it, as it works in the [playground](http://tinyurl.com/y2jbhf7u) just fine!

**Comment by azaroth42** [comment]
(Relabeling so we know to discuss on a call)
