### ISSUE TITLE
What's the use of 7.3?

### ISSUE THREAD

**Issue by azaroth42** [w3c/json-ld-syntax#256]
Doesn't this just redescribe anchors in HTML? It doesn't allow Dave to know Gregg, or anything like that?

I think the introduction to the section needs more explanatory text, especially a use case for when whatever this does would be useful.

**Comment by gkellogg** [comment]
The point of the example is that a URL can target a specific script element using the fragment identifier and that the extraction algorithm will only take that particular script element, and not merge together other elements.

If you think it's confusing that elements appear to be interrelated, when they're not, perhaps suggest better examples to use.

**Comment by azaroth42** [comment]
I think I must have been tired at this point, as that's indeed what the text of the first paragraph clearly states.

Suggest changing not the example in the the HTML, but the example in the description paragraph to reflect the technical example. Along the lines of:

> For example, given an HTML document located at http://example.com/document, a script element identified by "dave" can be targeted using the URL http://example.com/document#dave, and the data from any other elements would not be extracted
