### ISSUE TITLE
Missing keywords in 9.15 & 9.16

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-syntax#262]
## 9.15:

As far I could see, both `@propagate` and `@protected` can appear as part of a context definition. Shouldn't it appear in 9.15, alongside `@language`, `@base`, etc.?

Also, the expanded term definition should also include `@protected`.

## 9.16

`@protected` is missing

**Comment by pchampin** [comment]
Yes, I also noticed that very recently. I'll attend to it.

NB: `@import` is also missing from 9.15

**Comment by gkellogg** [comment]
WG [resolved to close the issue as complete](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-10-18-json-ld#resolution2).
