### ISSUE TITLE
Flagging an action for CR (RDF vocabulary file update)

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-syntax#263]
Just flagging the action: when we go to CR, the http://www.w3.org/1999/02/22-rdf-syntax-ns document should be updated to include `rdf:JSON` (plus the new terms defined by the addition of `@direction`).

cc @swickr

**Comment by gkellogg** [comment]
Also `i18n` namespace. and `rdf:CompoundLiteral`, `rdf:language`, and `rdf:direction`.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-12-06-json-ld#section4-3).

- No actions or resolutions
<details><summary><i class="differentiate">View the transcript</i></summary>
Flagging an action for CR <a href="https://github.com/w3c/json-ld-syntax/issues/263">https://github.com/w3c/json-ld-syntax/issues/263</a><br/>
Benjamin Young: Ivan do you want to explain this one?<br/>
Gregg Kellogg: We need to update the ontology for adding rdf:JSON<br/>
… also the terms for direction<br/>
Ivan Herman: This is when CR is done, gkellogg and I can do this<br/>
Benjamin Young: there’s no issue with us adding to rdf namespace<br/>
Ivan Herman: no additional process<br/>
… the only thing that’s a question is whether to do it now, or at PR<br/>
Dave Longley: I argue for doing it now … we’re using it now<br/>
Gregg Kellogg: I think it would be useful to do. If it went away from the spec, it wouldn’t really ever change<br/>
… the other two terms are properties … an i18n datatype that we’ve added<br/>
Ivan Herman: It’s in i18n not rdf<br/>
… we’ll need to create a separate file<br/>
Gregg Kellogg: the other ones in the blank node have been eliminated<br/>
Ivan Herman: We’ll have to look at it<br/>
… the i18n one … what URL do we use?<br/>
Gregg Kellogg: namespace is ns/i18n#<br/>
… which serves as base for adding fragments that specify the direction and language<br/>
Ivan Herman: okay the ns is fine, just need to create the file<br/>
Gregg Kellogg: the namespace doesn’t already exist … a new ns document<br/>
Ivan Herman: when we get the decision there might be a comment … don’t know. Will find out if there’s process about adding a new /ns file but i don’t think so<br/>
Gregg Kellogg: We still have 10.4 … for rdf namespace.<br/>
Ivan Herman: Yes, that’s not a problem<br/>
Benjamin Young: That’s weird that we can add to other people’s namespace?<br/>
Ivan Herman: It’s controlled by w3c<br/>
Benjamin Young: I expected more process<br/>
Rob Sanderson: just to note that in the annotation WG and in the social WG<br/>
… we added non-binding notes to explain how to add to the namespace<br/>
… by requiring that there should be discussion with the existing CG for those groups<br/>
… they’re meant to be polite requests<br/>
… not enforcement steps<br/>
… we did that because of this more flexible process<br/>
Gregg Kellogg: We’ve done this for the relevant groups<br/>
… we sent out about proposals for direction and with i18n wg<br/>
Ivan Herman: As you already have that, can you make a short list of the things we have to add<br/>
… and email so I can forward to Ralph so we have clarity, and if he sees any issues<br/>
… after the call, please<br/>
Benjamin Young: That’s helpful :)<br/>
Gregg Kellogg: Some NS docs are multiple, it’s not always apparent when you look at the ns that there’s multiple documents. Need to update all the relevant things<br/>
Ivan Herman: rdf ns doc is only one<br/>
… for i18n I’ll do turtle, rdf/xml and set up the usual conneg tricks<br/>
Benjamin Young: Thanks for all that!<br/>
</details>

**Comment by gkellogg** [comment]
Note my [proposed namespace updates](https://lists.w3.org/Archives/Public/public-json-ld-wg/2019Dec/0004.html).

```turtle
rdf:JSON a rdfs:Datatype ;
	rdfs:label “JSON" ;
	rdfs:comment "The datatype of RDF literals storing JSON content" ;
	rdfs:subClassOf rdfs:Literal ;
	rdfs:isDefinedBy <http://www.w3.org/1999/02/22-rdf-syntax-ns#> ;
	rdfs:seeAlso <https://www.w3.org/TR/json-ld11/#the-rdf-json-datatype> .

rdf:CompoundLiteral a rdfs:Resource ;
	rdfs:label "CompoundLiteral" ;
	rdfs:comment "A class representing a compound literal." ;
	rdfs:subClassOf rdfs:Resource ;
	rdfs:isDefinedBy <http://www.w3.org/1999/02/22-rdf-syntax-ns#> ;
	rdfs:seeAlso <https://www.w3.org/TR/json-ld11/#the-rdf-compoundliteral-class-and-the-rdf-language-and-rdf-direction-properties> .

rdf:language a rdf:Property ;
	rdfs:label "language" ;
	rdfs:comment “The language component of a CompoundLiteral." ;
	rdfs:domain rdf:CompoundLiteral ;
	rdfs:isDefinedBy <http://www.w3.org/1999/02/22-rdf-syntax-ns#> ;
	rdfs:seeAlso <https://www.w3.org/TR/json-ld11/#the-rdf-compoundliteral-class-and-the-rdf-language-and-rdf-direction-properties> .

rdf:direction a rdf:Property ;
	rdfs:label "direction" ;
	rdfs:comment “The direction component of a CompoundLiteral." ;
	rdfs:domain rdf:CompoundLiteral ;
	rdfs:isDefinedBy <http://www.w3.org/1999/02/22-rdf-syntax-ns#> ;
	rdfs:seeAlso <https://www.w3.org/TR/json-ld11/#the-rdf-compoundliteral-class-and-the-rdf-language-and-rdf-direction-properties> .
```

and for i18n:

```turtle
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix dc: <http://purl.org/dc/elements/1.1/> .

<https://www.w3.org/ns/i18n#> a owl:Ontology ;
	dc:title "The I18N Namespace" ;
	dc:description “""
            The i18n namespace is used for describing combinations of language tag and base direction in RDF literals.
            It is used as an alternative mechanism for describing the BCP47 language tag and base direction of RDF literals
            that would otherwise use the xsd:string or rdf:langString datatypes.
        """;
	rdfs:seeAlso <https://www.w3.org/TR/json-ld11/#the-i18n-namespace> .
```

**Comment by davidlehn** [comment]
Two quick minor issues:
- Add period to rdf:JSON comment.
```diff
 	rdfs:label “JSON" ;
-	rdfs:comment "The datatype of RDF literals storing JSON content" ;
+	rdfs:comment "The datatype of RDF literals storing JSON content." ;
```
- i18 description has a goofy quote.
```diff
 	dc:title "The I18N Namespace" ;
-	dc:description “""
+	dc:description """
```

**Comment by TallTed** [comment]
There are multiple instances (I see three) of the "smart" doublequote `“` which should all be changed to the "dumb" `"`.

**Comment by gkellogg** [comment]
> There are multiple instances (I see three) of the "smart" doublequote `“` which should all be changed to the "dumb" `"`.

Stupid "smart" quotes in my Mac email, from which I created the initial message; I'll fix inline.

**Comment by iherman** [comment]
I believe `rdf:CompoundLiteral a rdfs:Resource ;` should be, instead, `rdf:CompoundLiteral a rdfs:Class` ;

**Comment by iherman** [comment]
I have made the changes _on my machine_. See the [diff](https://www.w3.org/1999/02/22-rdf-syntax-ns.diff) and the (proposed) [html document](https://www.w3.org/1999/02/rdf-syntax.html). What I propose to do is:

1. update the rdf vocabulary in json-ld/rdf-xml/ttl formats along the diff above once the CR is published
2. send a mail to the semantic-web mailing list
    1. informing them about the changes on the vocab file
    2. pointing them to  [html document](https://www.w3.org/1999/02/rdf-syntax.html) and asking form comments
3. if 2.ii. above is o.k. with the community, put that document to `22-rdf-syntax-ns.html` and update the `.htaccess` file

The only concern I have is that applications may access the vocabulary file _without_ checking the return media-type, expecting to receive an RDF syntax and receiving an HTML file instead. Although the HTML file _includes_ the JSON-LD format of the vocabulary (embedded via a `<script>` element) such applications may still fail. Of course, that behaviour (ie, not checking the returned media type) is a bug, but they could get by in the past 20+ years and we could break them. If we do get remarks about that from the semantic-web crowd, we may have to abort point (3) above.

Cc: @swickr @gkellogg @draggett

**Comment by swickr** [comment]
I'm inclined to be conservative w.r.t. adding the .html there but let's see how the community feels.

**Comment by iherman** [comment]
- I have updated the vocabulary and sent a mail to the semantic web mailing list:
    - https://lists.w3.org/Archives/Public/semantic-web/2019Dec/0027.html
- I have also sent out a separate mail to the list on the HTML version:
    - https://lists.w3.org/Archives/Public/semantic-web/2019Dec/0028.html

However, the HTML version issue is not a problem of the JSON-LD Working Group, so I will close this issue as completed.
