### ISSUE TITLE
Description of `@type` in 9.16 should mention its use as a key on context

### ISSUE THREAD

**Issue by pchampin** [w3c/json-ld-syntax#269]
This will be tricky, because the use of `@type` in a context definition is very different different from its use in other context. In particular, the sentence

> The value of the `@type` key MUST be a term, absolute IRI, a relative IRI, or a compact IRI (including blank node identifiers).

is not true for the "context definition" case...

**Comment by gkellogg** [comment]
The next sentence the definition of `@type` you cite says "Within an expanded term definition, its value may also be either `@id` or `@vocab`." Is this not adequate?

**Comment by pchampin** [comment]
Sorry, the title of the issue is not very explicit.

I was referring to this kind of context:
```
{
  "@context" {
    "@type": { "@container": "@set" }
  }
}
```

which is not covered by 9.16, AFAICT.

**Comment by gkellogg** [comment]
WG [resolved to close the issue as complete](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2019/2019-10-18-json-ld#resolution2).

**Comment by azaroth42** [comment]
WG agrees
