### ISSUE TITLE
Graph id-s in the examples

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-syntax#27]
In all examples in section 4.15 on Named Graphs, the id-s of named graphs are blank nodes. This is not at all the way named graphs are used in practice and may be misleading for the user. We should use real URL-s whenever possible.

As a misleading example consider 4.15.1, where the blank node ID `_:claim` is used. For a reader who is not fully versed in RDF this _may_ give the impression that the blank node's ID has some semantic meaning, just like URL-s may have. A similar misleading example is the usage of `_:manu` and `_:gregg` in example 79.

**Comment by gkellogg** [comment]
Well, named graphs are used this way pretty exclusively in Verifiable Credentials, so I'd be careful of such a blanket statement, and certain settings are designed for anonymous named graphs (e.g. `"@container": "@graph"`). While, [Named Graph Indexing](https://w3c.github.io/json-ld-syntax/#named-graph-indexing) favors graphs that are named with IRIs.

But, in [4.15 Named Graphs](https://w3c.github.io/json-ld-syntax/#named-graphs), the examples using `@graph` and `_:graph` could certainly use an IRI instead.

**Comment by iherman** [comment]
At this moment, VC-s are indeed a major usage. But named graphs are used in many different situtions in major data stores, where the blank node usage may be almost irrelevant. I think, in general, we should use URI-s (oops, URL-s 😄) when we can. Having _some_ examples is fine and probably necessary, of course.

However, I would be particularly careful about the usage of “semantically named” blank node id-s. I would very much try to avoid them, to avoid giving a wrong impression to non-RDF-aware readers...

**Comment by iherman** [comment]
Note, b.t.w., that Datasets in SPARQL do _not_ allow blank nodes as graph identifiers. If the goal of an encoding of a graph in JSON-LD is to, at some point, feed this into a, say, SPARQL CONSTRUCT, then blank nodes are not allowed. One more reasons to be very careful about them...
