### ISSUE TITLE
JSON literal term definition markup.

### ISSUE THREAD

**Issue by davidlehn** [w3c/json-ld-syntax#278]
The JSON literal term definition has two `data-cite` attributes.  I'm not sure what it's supposed to look like or link to.
https://github.com/w3c/json-ld-syntax/blob/6528a7482e1b6676627b38263a034b36b2ce05e2/common/terms.html#L254

**Comment by gkellogg** [comment]
It’s a bug, but should be harmless, as ReSpec will only process one.

**Comment by davidlehn** [comment]
Is it supposed to even have that `data-cite` markup there?  Shouldn't that be an `<a>` or something and link elsewhere?

**Comment by gkellogg** [comment]
We need to use data-cite pretty pervasively, to make sure that the proper term URLs are generated. There is code in common/common.js that removes it from definitions that use data-cite where the short-name is the same as the short-name of the spec, which was necessary to work around a ReSpec bug, and to preserve document-local fragment references.

**Comment by gkellogg** [comment]
Seems to have been handled in a previous commit.
