### ISSUE TITLE
Pick a better keyword for @nest

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-syntax#3]
People haven’t been satisfied with the @nest term for describing nested properties, although nothing better has come along.

Original issue was [Ignoring semantically meaningless nesting #246](https://github.com/json-ld/json-ld.org/issues/246).

**Comment by gkellogg** [comment]
I think that ship has sailed.

**Comment by azaroth42** [comment]
+1 to closing. At best it's a bikeshed issue, at worst it's an unnecessary incompatibility for systems that implement the draft spec.

**Comment by azaroth42** [comment]
Closing, won't fix, but without prejudice if someone comes up with a significantly better name.
Rationale: Unnecessary bikeshedding.

WG Resolution: https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-07-27-json-ld#section2-6
