### ISSUE TITLE
Confusing statement on aliasing keywords

### ISSUE THREAD

**Issue by hsolbrig** [w3c/json-ld-syntax#308]
The sentence "Other than for @type, properties of expanded term definitions where the term is a keyword result in an error. " (Section 4.1.6) is difficult to understand.  Would it be possible to add an example of an "@type" and another keyword to clarify the intent?

**Comment by gkellogg** [comment]
There's a note in Aliasing Keywords: "Aliased keywords MUST NOT be used within a context, itself.", but it's not normative, and shouldn't use normative language.

There are a number of places in keyword definitions where we say --term-- MUST NOT be aliased, and we probably shouldn't make this statement. It's not that there's something special about a keyword (other than `@context`) that prevents it from being aliased, it's that nothing in a context definition can be aliased. The grammar and term definition sections should make this clear normatively. We should remove statements we've added about not aliasing keywords other than `@context` and clarify that keywords may be aliased in the body of a JSON-LD document exclusive of a context or term definition.

**Comment by gkellogg** [comment]
There is already a reference to `#using-set-with-type` which has such an example. I've updated the text to also say that there are examples there, in addition to further detail.

**Comment by azaroth42** [comment]
Editorial work resolved by #312
