### ISSUE TITLE
Alias statements about `@base` are inconsistent

### ISSUE THREAD

**Issue by hsolbrig** [w3c/json-ld-syntax#309]
Section 4.6.1 says "Each of the JSON-LD keywords, except for `@context`, may be aliased to application-specific keywords."  Section 9.16 Keywords says, however, that "The `@base` keyword MUST NOT be aliased, and MAY be used as a key in a context definition."  Can both of these statements be true?

**Comment by gkellogg** [comment]
It seems more clarification is needed. Within a context, keyword aliases may not be used. Within the body of a document, all keywords other than `@context` May be aliased. Of course, `@base` only appears in the context, along with some other keywords.

**Comment by hsolbrig** [comment]
How about something along the lines of "Any JSON-LD keyword that can appear in a _node object_ may be aliased with the exception of `@context`"?

**Comment by gkellogg** [comment]
It’s not just node objects, but really anywhere outside of the context. I thought we had wording about this, maybe obscured from 1.0.

**Comment by gkellogg** [comment]
See #308; we should simplify these and normatively prohibit using aliased keywords in contexts or term definitions.

**Comment by azaroth42** [comment]
Resolved by #312
