### ISSUE TITLE
Typo in reference to ECMASCRIPT equality testing

### ISSUE THREAD

**Issue by kasei** [w3c/json-ld-syntax#321]
The discussion of the value space of [the rdf:JSON Datatype](https://www.w3.org/TR/json-ld11/#the-rdf-json-datatype) says:

> Otherwise, if A and B satisfy the Strict Equality Comparison defined in Section 7.2.15 in [ECMASCRIPT].

This seems to be a typo as both the links in this sentence point to section 7.2.16 ("Strict Equality Comparison") of the ECMASCRIPT spec.

**Comment by kasei** [comment]
The link to 7.2.12 also seems to be mis-numbered (it actually links to 7.2.13).

**Comment by gkellogg** [comment]
Updated in #322. @kasei please acknowledge.

**Comment by kasei** [comment]
@gkellogg looks good. Thanks.
