### ISSUE TITLE
Keyword `@preserve` missing?

### ISSUE THREAD

**Issue by pchampin** [w3c/json-ld-syntax#332]
I just discovered that the API and Framing document have a few mentions of `@preserve`, but this keyword(?) is never mentioned in the Syntax document...

**Comment by gkellogg** [comment]
Should be `@proteced`; we may have gone back and for on this, or I may have just had some confusion.

**Comment by gkellogg** [comment]
No, I take that back, `@preserve` is a framing keyword, used internally to preserve values that might be lost in compaction (e.g., `null`). It is not available for users, but just used internally.

Perhaps some expansion in the framing document on the use of `@preserve` within the [Default Content](https://w3c.github.io/json-ld-framing/#default-content) section.

**Comment by azaroth42** [comment]
Editorial only?

**Comment by gkellogg** [comment]
Framing didn’t require a new approval, as the changes were only Editorial. Syntax had a normative change, as did API, due to a change in how the JSON literal was defined.

Gregg Kellogg
gregg@greggkellogg.net
