### ISSUE TITLE
@type as @container:@set?

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-syntax#34]
The purpose of the `@container:@set` functionality (AFAIU) is to ensure that the output is consistent in shape. Thus if there can ever be multiple values, the structure is always an array.

There are two situations in which this functionality could be desirable but is currently not possible:

1.  `@type` As it's a keyword, we can only alias it (e.g. as `type`) but not define it to have `@container:@set` functionality. Meaning that there's a gotcha waiting to happen for ontologies that require or use multiple classes for a single resource instance. See [playground](https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%7B%22cls%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Fclass%22%7D%2C%22type%22%3A%7B%22%40id%22%3A%22%40type%22%2C%22%40container%22%3A%22%40set%22%7D%7D%2C%22%40id%22%3A%22foo%22%2C%22type%22%3A%22cls%22%7D&context=%7B%22%40context%22%3A%7B%22cls%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Fclass%22%7D%2C%22type%22%3A%7B%22%40id%22%3A%22%40type%22%2C%22%40container%22%3A%22%40set%22%7D%7D%7D)
2.  `@context` Less useful, but `@context` will also compact to a single string/object when there might be multiple contexts.  See [playground](https://json-ld.org/playground/#startTab=tab-compacted&copyContext=true&json-ld=%7B%22%40context%22%3A%5B%7B%22cls%22%3A%7B%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Fclass%22%7D%2C%22type%22%3A%7B%22%40id%22%3A%22%40type%22%2C%22%40container%22%3A%22%40set%22%7D%7D%5D%2C%22%40id%22%3A%22foo%22%2C%22type%22%3A%22cls%22%7D)

`@context` modifying itself seems particularly strange, but the inconsistency for `@type` seems solvable if the restrictions in its definition were loosened?

Original issue [@type as @container:@set? #512](https://github.com/json-ld/json-ld.org/issues/512).

(Edit: Note that the playground links demonstrate that these do not work as one might expect, due to the keyword definitions of @type and @context)

**Comment by dlongley** [comment]
Seems like a useful feature to allow `@container: @set` for `@type`.

**Comment by gkellogg** [comment]
We should consider allowing any keyword that can take multiple values, such as `@graph`, to allow it's container model to be updated. A use case outlined in https://github.com/w3c/json-ld-syntax/issues/30#issuecomment-401941284 would do the following:

```json
{
  "@context": {
    "dataset": {"@id": "@graph", "@container": ["@graph", "@id"]}
  },
```

It should allow the following as well:


```json
{
  "@context": {
    "@graph": {"@container": ["@graph", "@id"]}
  },
```

This may need some extra sanity checking, as `@list`, or anything not including `@graph` would be prohibited.

**Comment by azaroth42** [comment]
[Resolution](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-08-17-json-ld#resolution3) on WG call of 2018-08-17:  `@type` (or an alias of it) can be set to be a `@container` (only), and if so it can have only the value of `@set`.  This allows the use case of requiring the field to always be an array for consistency, even if there's only one value.

And [secondly](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-08-17-json-ld#resolution4), that we will not change @context as the processing would be extremely convoluted for minimal value.

**Comment by azaroth42** [comment]
Interestingly, [someone](https://github.com/gkellogg) proposed this be allowed back in 2012:  https://github.com/json-ld/json-ld.org/issues/80#issuecomment-5420799   😀
