### ISSUE TITLE
Editorial: Incorrect internal spec reference for @vocab section

### ISSUE THREAD

**Issue by dbooth-boston** [w3c/json-ld-syntax#341]
At the end of section 1.4 in the March 23, 2020 editor's version of 1.1 syntax, the description of "vocabulary mapping" says: "See the Value Objects section of JSON-LD 1.1 for a normative description."
https://w3c.github.io/json-ld-syntax/#terminology

Shouldn't that be pointing to the "Default Vocabulary" section instead?
https://w3c.github.io/json-ld-syntax/#default-vocabulary

**Comment by dbooth-boston** [comment]
Hmm, that might not be the right section either, because it is non-normative.  Not sure what is the correct normative section to reference.

**Comment by gkellogg** [comment]
It looks like that "See the Value Objects section" sentence belongs with the previous definition for "value objects".

This definition should probably point to [Context Definitions](https://w3c.github.io/json-ld-syntax/#context-definitions).

**Comment by gkellogg** [comment]
Thanks for noticing @dbooth-boston. Please let us know if it is properly solved in PR #342.
