### ISSUE TITLE
FYI: anchors aren't in .html thus cannot be easily validated

### ISSUE THREAD

**Issue by yarikoptic** [w3c/json-ld-syntax#343]
JS-powered https://w3c.github.io/json-ld-syntax is really nice, but we encountered difficulty with linkchecker to verify that URLs we use are still correct.  The reason is that it seems that the anchors are populated and/or handled by JS, so anything which just downloads the page without running JS would fail to find those id's.

E.g. [in our case](https://github.com/bids-standard/bids-specification/pull/439#issuecomment-609920845) it is https://w3c.github.io/json-ld-syntax/#named-graphs  link, for which there is no "named-graphs" id in the actual source .html:

```shell
$> wget -q -O- 'https://w3c.github.io/json-ld-syntax/#named-graphs' | grep 'named-graphs' | grep -v 'href="#named-graphs"'
$> 
```

I am not sure if there is an easy workaround at any level, or may be some alternative link which would lead to an .html version with those anchors?

PS Please pardon my ignorance if it is something really simple ;)

**Comment by gkellogg** [comment]
You should use the published version at https://www.w3.org/TR/json-ld11/, which is the result of processing the editors draft and resolving all such links.

The editors draft is in a "raw" format, and makes use of [ReSpec](https://github.com/w3c/respec/wiki). It does provide some features that the published version doesn't (unfortunately), such as highlighted variables within algorithms. ReSpec is widely used for W3C specifications.

There is a processes used in our continuous integration to create a fully resolved version from the source in [.travis-ci.yaml](https://github.com/w3c/json-ld-syntax/blob/master/.travis.yml), if you really want to work off of the editor's draft:

https://github.com/w3c/json-ld-syntax/blob/a65dd9acf04bce870392afd2c074c44bf86f9607/.travis.yml#L21-L33

**Comment by gkellogg** [comment]
[Resolved to close](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2020/2020-04-17-json-ld#resolution1), as the final form will have anchors in the html.

**Comment by yarikoptic** [comment]
Thank you @gkellogg !
