### ISSUE TITLE
Where is rdf:JSON specified? 

### ISSUE THREAD

**Issue by dr-shorthair** [w3c/json-ld-syntax#353]
I see reference to it here: https://w3c.github.io/json-ld-syntax/#the-rdf-json-datatype 
but can't track down any mention in what I think are the relevant sections in the RDF or RDFS recs 
https://www.w3.org/TR/rdf11-concepts/#section-Datatypes 
https://www.w3.org/TR/rdf-schema/#ch_literal

**Comment by akuckartz** [comment]
This section is normative: https://w3c.github.io/json-ld-syntax/#the-rdf-json-datatype

But it seems to be somewhat irritating that rdf:JSON is specified in _that_ document.

**Comment by iherman** [comment]
@dr-shorthair, as @akuckartz referred to, this datatype is _defined_ by the JSON-LD specification. The RDF(S) namespaces are "controlled" by W3C, and not necessarily by a specific Working Group (which does not exist at the moment), so it is perfectly fine to add a new term to that namespace defined by another WG.

If and when an RDF WG is re-chartered by W3C, that _may_ add that datatype to the core RDF _specifications_ to make the reference documents complete. But that is sometimes into the future.

**Comment by dr-shorthair** [comment]
Ok - thanks.
