### ISSUE TITLE
Typo in syntax document

### ISSUE THREAD

**Issue by hsolbrig** [w3c/json-ld-syntax#358]
Section 9.3 Frame objects has the line:
`A frame object MAY include an entry with the key @embed with any value from @always, @list, and @never.`

This should read
`A frame object MAY include an entry with the key @embed with any value from @always, @once, and @never.`  (list -> once)

**Comment by davidlehn** [comment]
Fixed in https://github.com/w3c/json-ld-syntax/pull/359.
