### ISSUE TITLE
Support recursive @list usage

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-syntax#36]
From [Should we support lists of lists?](https://github.com/json-ld/json-ld.org/issues/52)

We did not support recursive RDF lists in 1.0 due to perceived complexity and lack of a use case. Since then there are numerous use cases that can make use of recursive lists in JSON-LD, and it goes further towards full idiomatic support of RDF 1.1 in JSON-LD.

Changes to the syntax document are minimal, there are substantial API implications.

**Comment by gkellogg** [comment]
I'm actively working on tests and algorithms to support this now; compaction and expansion are reasonably easy. A review of Flattening shows some errors in that algorithm, and potentially missing tests. Biggest changes will be to the FromRDF algorithm, as the list support there is complicated already.

**Comment by gkellogg** [comment]
There are numerous tests in the API PR w3c/json-ld-api#16 that show how this looks.

Compacted list containing embedded lists, simply continues to expand embedded arrays:

```json
{
  "@context": {"foo": {"@id": "http://example.com/foo", "@container": "@list"}},
  "foo": [["baz"]]
}
```

expands to

```json
[{
  "http://example.com/foo": [{"@list": [{"@list": [{"@value": "baz"}]}]}]
}]
```

which is equivalent to the following Turtle

```turtle
[<http://example.com/foo> (("baz"))] .
```

Algorithms support arbitrary depth and mixed elements.

**Comment by iherman** [comment]
I do not have any problem having this but I think the syntax document should include some explicit statements and examples for the case of lists of lists. It is not clear from the text in the syntax document whether the syntax above is permitted or not...

**Comment by gkellogg** [comment]
I started with the API, to make sure I had a solution that worked. I still need to update the syntax document for grammar, explanation and examples, which I’ll do presently.

**Comment by azaroth42** [comment]
Given this issue is syntax, and we [agreed to include it](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-08-03-json-ld#section4) in the syntax, flagging as editorial and removing needs discussion.
