### ISSUE TITLE
Possible typos in Json-ld 1.1

### ISSUE THREAD

**Issue by shujikamitsuna** [w3c/json-ld-syntax#364]
Hi. This is KAMITSUNA Shuji @ Japan.
I'm translating the Json-ld 1.1 into Japanese and found possible typos below.

1) Sec. 1.3, in the description of "markup definition reference": "A references" might be "A reference" or "References".
2) Sec. 1.4, in the description of "embedded context": "a nested properties" might be "a nested property" or "nested properties".
3) Sec. 1.4, in the description of "graph object": "it it" might be "if it".
4) Sec. 1.4, in the description of "language map": "An language" might be "A language".
5) Sec. 1.6, in the third paragraph: "kinds of resource" might be "kinds of resources".
6) Sec. 4.1.2, in the paragraph below ex. 24: "an map" might be "a map".
7) Sec. 4.1.5, in the paragraph above NOTE: "a expanded" might be "an expanded" - same expression can be found in the sec. 4.1.6, and 9.16.
8) Sec. 4.1.8, in the paragraph below ex.46: "calls for" might be "call for".
9) Sec. 4.2.4, in the paragraph below ex.68: period (.) might be missing after "with the two strings 花澄 and 科学者".
10) Sec. 4.3, in the NOTE below ex. 79: "generates" might be "generate".
11) Sec. 4.3.1, in the paragraph below ex.84: "includes" might be "include".
12) Sec. 4.6, in the second paragraph: "iterating though" might be "iterating through".
13) Sec. 8, in the sentence above ex.149: "an property" might be "a property".
14) Sec. 8: "Data Round Tripping) in" might be "Data Round Tripping in" - closing bracket might be unnecessary.
15) Sec. 9.10, in the first sentence: "were" might be "where".
16) Sec. 9.12, in the second paragraph: "is contains" might be "contains" or "is".
17) Sec. 9.16, in the second paragraph: "MAY NOT used" might be "MAY NOT be used".
18) Sec. A.1, in the description of "weiblich | de" and "female | en": "an language-tagged" might be "a language-tagged".
19) Sec. A.1: the latter description of "http://example.com/graphs/1" might be "http://example.com/graphs/2".

Thank you very much for the great specification!

Best regards,

**Comment by gkellogg** [comment]
@shujikamitsuna Thanks for noticing these; some of them indirectly relate to the other documents as well.

In starting to work on them, I see that ReSpec has (of course) changed, and is highlighting other issues with our (ab-)use of ReSpec, which I'll also need to address.

It's great that you're working on a Japanese translation of this, and please reach out for any other issues or clarifications.

**Comment by gkellogg** [comment]
Summary: Miscellaneous spelling and grammar fixes suggested by @shujikamitsuna.
