### ISSUE TITLE
Typo "it it" 

### ISSUE THREAD

**Issue by EdgarSchouten** [w3c/json-ld-syntax#368]
Note that a node object may also represent a named graph **it** it includes other properties. See the Graph Objects section of JSON-LD 1.1 for a normative description.

Page: https://www.w3.org/TR/json-ld11/

Note that a node object may also represent a named graph **if** it includes other properties. See the Graph Objects section of JSON-LD 1.1 for a normative description.

**Comment by pchampin** [comment]
thanks @EdgarSchouten 

This was reported already in #364, and has already been fixed in the [latest editor's draft](https://json-ld.github.io/json-ld-star/).

**Comment by davidlehn** [comment]
(Updated comment to fix editor's draft link to syntax doc vs json-ld-star doc.)

**Comment by pchampin** [comment]
:sweat_smile: thanks @davidlehn
