### ISSUE TITLE
"HTTP document"

### ISSUE THREAD

**Issue by pchampin** [w3c/json-ld-syntax#369]
§6.2 says "HTTP document" while it should says "HTML document"

**Comment by gkellogg** [comment]
Summary: Updated "HTTP document" to "HTML document" in §6.2.

**Comment by davidlehn** [comment]
Do simple typo errata need to also be documented elsewhere?

**Comment by gkellogg** [comment]
But, for completeness, it may need an entry in the "Changes since Recommendation" section.
