### ISSUE TITLE
Using @context on children of a mapped vocabulary

### ISSUE THREAD

**Issue by PonteIneptique** [w3c/json-ld-syntax#392]
Hello :)
First of all, I am very very not used to JSON-LD `@context`, I have been on the receiving end of JSON-LD content more than on writing useful `@context`.

In the context of our API Specification, we are trying to figure out how to have the `@language` property under a `dct:*` property mapped to `language` while keeping `language` at the "root" level of the mapped vocabulary to `dct:language`.

As this is very confusing, here is an example:

```json
{
  "dublincore": {
    "title": [
      {"language": "en", "value": "Hello"} // This language should be @language
    ],
    "language" : ["en"] // This language should be dct:language
  }
}
```

My current tries drove me to something like this

```json
  "@context": {
    "dct": "http://purl.org/dc/terms/",
    "dts": "https://w3id.org/dts/api#",
    "language": "@language",
    "value": "@value",
    "dublincore": {
      "@id": "dts:dublincore",
      "@context": {
        "@vocab": "http://purl.org/dc/terms/",
        "language": "http://purl.org/dc/terms/language",
        "null": { // This obviously does not work
          "@context": {
            "language": "@language"
          }
        }
      }
    }
  }
```

I'd be most thankful if you could help us on this specific task.

 If this is the wrong canal for such a question, please accept my apologies.

**Comment by pchampin** [comment]
I don't think there is an easy way to achieve that, unfortunately.

One way out would be to *not* use the same attribute name, e.g. use `lang` (as in HTML) as an alias to `@language` , and `language` for `dct:language`.

If using the same attribute is unavoidable, I would push the alias down to *every* property that needs it ([example in playground](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%7B%22dct%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%22%2C%22dts%22%3A%22https%3A%2F%2Fw3id.org%2Fdts%2Fapi%23%22%2C%22value%22%3A%22%40value%22%2C%22dublincore%22%3A%7B%22%40id%22%3A%22dts%3Adublincore%22%2C%22%40context%22%3A%7B%22%40vocab%22%3A%22dct%3A%22%2C%22title%22%3A%7B%22%40context%22%3A%7B%22language%22%3A%22%40language%22%7D%7D%2C%22description%22%3A%7B%22%40context%22%3A%7B%22language%22%3A%22%40language%22%7D%7D%7D%7D%7D%2C%22dublincore%22%3A%7B%22title%22%3A%5B%7B%22language%22%3A%22en%22%2C%22value%22%3A%22Hello%22%7D%5D%2C%22language%22%3A%5B%22en%22%5D%7D%7D&frame=%7B%7D&context=%7B%7D)), but that's induces quite some redundancy.

If you still want to alias `language` to `@language` at the top level, you need to override it in the scoped context of `dublincore`, and then override it again for every property expecting a langString ([example in playground](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%7B%22dct%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%22%2C%22dts%22%3A%22https%3A%2F%2Fw3id.org%2Fdts%2Fapi%23%22%2C%22language%22%3A%22%40language%22%2C%22value%22%3A%22%40value%22%2C%22dublincore%22%3A%7B%22%40id%22%3A%22dts%3Adublincore%22%2C%22%40context%22%3A%7B%22%40vocab%22%3A%22dct%3A%22%2C%22language%22%3A%22dct%3Alanguage%22%2C%22title%22%3A%7B%22%40context%22%3A%7B%22language%22%3A%22%40language%22%7D%7D%2C%22description%22%3A%7B%22%40context%22%3A%7B%22language%22%3A%22%40language%22%7D%7D%7D%7D%7D%2C%22dublincore%22%3A%7B%22title%22%3A%5B%7B%22language%22%3A%22en%22%2C%22value%22%3A%22Hello%22%7D%5D%2C%22language%22%3A%5B%22en%22%5D%7D%7D)).

**Comment by PonteIneptique** [comment]
Thanks @pchampin, that's definitely what I thought. I guess we'll go for `@lang` in the main `@context` then :)
