### ISSUE TITLE
Propose `@documentation` for providing URL of resource documenting context or frame

### ISSUE THREAD

**Issue by tcole3** [w3c/json-ld-syntax#42]
The discussion surrounding Issue #32 (Is there a way to define additional metadata in JSON-LD `@context`?) identified possible use cases for wanting to provide comments or documentation (e.g., metadata) about JSON-LD context and framing documents. The [JSON-LD 1.0 Recommendation](https://www.w3.org/TR/json-ld/#the-context) (and the [JSON-LD 1.1 Community Report](https://json-ld.org/spec/latest/json-ld/#the-context)) anticipate the value of `@context` documentation: 

> External JSON-LD context documents may contain extra information located outside of the `@context` key, such as documentation about the terms declared in the document. Information contained outside of the `@context` value is ignored when the document is used as an external JSON-LD context document. 

However, this method does not support documentation of context included inline in a JSON-LD instance, does not facilitate the reuse of pre-existing vocabulary and ontology documentation already available online, and does not provide an option for human-readable documentation of terms declared in the context document (or documentation of the associated ontology as a whole), nor for machine readable documentation in a format other than JSON-LD. Additionally, this mechanism is of no help for those wanting to describe the logic and flow of a framing document.

Adding `@documentation` as a key (with range URL) available only in context and framing documents would allow including documentation by reference. Taking schema.org context document as an example, any of the following might be reasonable values for `@documentation`:

- https://schema.org/docs/documents.html (incomplete, human-readable list of documentation)
- https://schema.org/docs/full.html (human-readable hierarchy view with links to RDFa term descriptions)
- https://schema.org/docs/schema_org_rdfa.html (RDFa documentation of schema.org vocabulary)
- https://schema.org/version/3.4/schema.rdf (RDF/XML documentation of schema.org vocabulary)
- https://schema.org/docs/schemaorg.owl (OWL documentation of schema.org vocabulary)

The latter 3 illustrations listed are all machine-actionable and provide (for example) domain and range information for each schema.org property, as well as sub-class relationships for schema.org Classes. 

Given the variety of ways that semantics are documented today, if `@documentation` were adopted for 1.1, my suggestion would be to avoid over-specifying what precisely the URL value links to - in other words I would define this new key such that any of the above 5 illustrations would be allowable values for `@documentation`. We probably also would need to agree (or not) that the value of `@documentation` is unary (no arrays of URLs) and would need to identify any other constraints on its value.  

Note, credit to @azaroth42 for suggesting `@documentation` in the course of issue #32 discussion, and please note that this issue is being raised concurrently with 2 or 3 other approaches, as an outgrowth of the decision to close issue #32.

**Comment by BigBlueHat** [comment]
In the case of Schema.org (at least), each term URL results in a human and machine readable HTML+RDFa representation of that term: https://schema.org/Thing (for example).

Given the above, what functionality or expectations would a `@documentation` term add in this scenario?
Or (conversely) what bugs or issues might it avoid?

**Comment by tcole3** [comment]
The folks behind schema.org have done a better than average job (in my opinion) of documenting their ontology, so possibly they would never bother with `@documentation` in their context document. However, it really depends on what's wanted and I'm not sure we'll know for sure until people have had the opportunity to use the proposed new key. So, for example, in the case of schema.org, the first link given above  (https://schema.org/docs/documents.html) might be their best choice as value for `@documentation`. This html page lists for the human reader a variety of ways to learn about schema.org terms and hierarchies collectively and in formats perhaps more amenable to some than html+rdfa, e.g., the list includes links to a view of the schema.org type hierarchy, an FAQ, a description of all schema.org properties in a single CSV, a getting started page, etc. 

But I would agree if could count on everyone to self-document all the terms declared in their context document with individual RDFa pages, there'd be less need for `@documentation`.

**Comment by azaroth42** [comment]
I think we need to scope where `@documentation` could appear:

* Only at the root of the tree
* In term definitions

I would be happy enough with only at the root of the tree, and only a single URI. That means it's clearly about the context, and not trying to over-reach into ontology definition.

**Comment by azaroth42** [comment]
Exactly.

And not:

```
{
  "@context": {
    "label": {
      "@id": "rdfs:label", 
      "@documentation": "https://www.w3.org/TR/rdf-schema/#ch_label"
    }
  }
}
```

**Comment by iherman** [comment]
I think we have to separate to use cases.

1. Documenting the context file, for which this may be a solution indeed. Easy to implement and use by any user who publishes context file(s). I am fine with it.
1. We also have the problem of users who want to comment/document the _data_. What do we offer for that use case?

I guess the answer to (2) is to use some existing vocabulary, like `rdf:comment` (or some DCMI equivalent). Which is fine, it also gets the value into the dataset with roundripping which is a cherry on the cake. However, it would require to spell out the full URL for `rdf:comment`, which is pain, or to extend the context part which, for many users, is not an option (I am considering authors who want to add metadata to a Web Publication using the [manifest definition](https://www.w3.org/TR/wpub/#wp-properties). What this may lead to is whether it'd make sense to introduce a, possibly stripped down version, of the [RDFa intial context notion](https://www.w3.org/2011/rdfa-context/rdfa-1.1), ie, a number of well established prefixes that are _always_ known to a JSON-LD processor? That means that _anybody_ without any prior knowledge, could use `rdf:comment` or `dct:description` in the data.

Maybe (probably) this deserves a separate issue.

**Comment by azaroth42** [comment]
WG consensus to close documentation issues, with a future action to consider best practices around documentation rather than syntax / normative requirements.

Resolution:
 * https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-08-10-json-ld#resolution3
