### ISSUE TITLE
Should we consider a simple initial context like in RDFa?

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-syntax#44]
(Spin-off from #42)

There may be a number of prefixes that we could 'predefine', i.e., having them part, formally, of an initial `@context`. This would simplify to encourage users to use terms from, say, DCMI, in a consistent manner for things like comments or descriptions, without requiring them to extend the context (which, for many authors, may be a challenge).

RDFa has a [similar notion](https://www.w3.org/2011/rdfa-context/rdfa-1.1) but I actually do _not_ think we should replicate that; we could make it much smaller and less dynamic. Taking into account the JSON-LD user community, I would probably restrict it to rdf, rdfs, xsd, cc, dc/dcterms, and schema. Extending this list could be restricted to future revisions of JSON-LD 1.1.

**Comment by azaroth42** [comment]
For reference, in 1.0 this was discussed here: https://github.com/json-ld/json-ld.org/issues/80

**Comment by gkellogg** [comment]
When discussed in 1.0 it became an issue when the context is re-defined using `@context: null` and was rejected. For those using `http://schema.org`, this is already done for them, which probably covers most uses.

**Comment by gkellogg** [comment]
[Resolved to close](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-08-24-json-ld#resolution4).

**Comment by azaroth42** [comment]
WG [resolved](https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-08-24-json-ld#resolution4) to close, won't fix, but to open a new issue to create a best practice for a suggested context that could be imported into other contexts.

**Comment by BigBlueHat** [comment]
The new issue opened to "create a best practice for a suggested context" https://github.com/w3c/json-ld-syntax/issues/59
