### ISSUE TITLE
Object-level @language

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-syntax#5]
Support the use of `”@language”: “foo”` as a shorthand for `{“@context”: {“@language”: “foo”}}`.

Original issue is [JSON-LD 1.1 Feature Request: Object-level @language #368](https://github.com/json-ld/json-ld.org/issues/368)

**Comment by gkellogg** [comment]
syntactic sugar which doesn’t help, IMHO

**Comment by azaroth42** [comment]
+1 to closing. Agree with @gkellogg that the sugar is unnecessary.

**Comment by azaroth42** [comment]
Closing, won't fix. Rationale: Unnecessary syntactic sugar.

WG Resolution: https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-07-27-json-ld#section2-5
