### ISSUE TITLE
Images should be accessible

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-syntax#51]
The spec contains a single image describing the data model ([An illustration of the data model](https://w3c.github.io/json-ld-syntax/linked-data-graph.png)), which is not accessible. Moreover, the embedded image is not scalable, and there's no description of the toolchain to recreate the PNG.

![image](https://user-images.githubusercontent.com/46296/44411506-817db780-a51b-11e8-9b99-debddfcf511e.png)

In CSVW, we used Keynote as the source of the images and a process (@iherman can comment) to turn images from Keynote into SVG and PNG. Images should be contained within a figure, with caption and reference to an [external description via `@longdesc`](http://w3c.github.io/csvw/metadata/properties.html). For example, from [CSVW Metadata](https://github.com/w3c/csvw/blob/gh-pages/metadata/index.html#L279-L281):

      <figure id="fig-properties" style="text-align:center">
        <img src="properties.svg" style="width: 75%" alt="Metadata Properties" longdesc="properties.html#imageDescription">
        <figcaption>Diagram showing the properties of different metadata descriptors (see the diagram in <a href="properties.svg">SVG</a> or <a href="properties.png">PNG</a> formats)</figcaption>
      </figure>

We should also consider other images that should be in the spec, and perhaps a simple mechanism for creating graphical representations of linked data graphs/datasets from examples.

**Comment by gkellogg** [comment]
One such tool may be https://github.com/trieloff/key2svg.

**Comment by iherman** [comment]
@gkellogg indeed. Which is of course suboptimal, because keynote works on macOS only. I realized, lately, that Google Drawings, which one can use though Google drive, does also a decent job in creating SVG. From that point on, we can use the same process as you described, but the sources become more widely available.

**Comment by gkellogg** [comment]
The only danger with Google Drawings that I can see is if they go away, for some reason, we've lost the source of the diagrams. Not really a bigger issue than we have already, since the spec only needs the produced graphics.

**Comment by BigBlueHat** [comment]
The SVG would be in the repo, so I wonder what (if anything) we'd loose after saving out of Google Drawings. There's also [Inkscape](https://inkscape.org/en/)--which is open source and awesome.

**Comment by davidlehn** [comment]
I'm a fan of Inkscape.  It was used to create the JSON-LD logo and buttons and such.  Minimal workflow info in the README and Makefile here:
https://github.com/json-ld/json-ld.org/tree/master/images

SVG font issues can sometimes be odd.  Like the logo text can get messed up if the right font isn't available.  Probably should be doing some embedded font or path conversion thing to handle that.  Consider that for these other images.
https://github.com/json-ld/json-ld.org/issues/388

**Comment by BigBlueHat** [comment]
> A warning: if SVG + CSS fonts are used, the image must be included into HTML using object and not img. Additional processing involving fetching resources is done only when the drawing comes via object.

Can you elaborate on this?

**Comment by BigBlueHat** [comment]
> @BigBlueHat @davidlehn there problems with inkspace for macOS. The direct download reports that the application has to be updated for Mac (I suspect it is not a 64 bit executable) and it would require me to install something else (quartz, I am not sure what it is); the homebrew version does not install, because there is an SHA256 mismatch in the package. I remember having looked at it before, and it was always problematic:-(

Guessing you tried the `.dmg` here? https://inkscape.org/en/release/0.92.2/mac-os-x/

XQuartz is an implementation of X Windows for the Mac: https://www.xquartz.org/ I'd moved to Mac from Linux, so having that was a forgone conclusion. 😄

**Comment by BigBlueHat** [comment]
I'd vote we keep a "working copy" of the SVG that uses the fonts, etc, and then a publish-friendly flattened one. We can keep both in the same repo to track changes, etc.

**Comment by iherman** [comment]
@BigBlueHat, on https://github.com/w3c/json-ld-syntax/issues/51#issuecomment-415021087: if you have an SVG file with linked fonts (ie, using the CSS url(.) command to get hold of the fonts) then:

- if you use `<img src="f.svg">` in the HTML, the font will _not_ be fetched and the drawing will go wrong
- if you use `<object data="f.svg">` in the HTML, things will work

The reason is something around whether the browser creates a full environment for the SVG or not and, it seems, that is not the case for img.I do not know the details...

**Comment by iherman** [comment]
> I'd vote we keep a "working copy" of the SVG that uses the fonts, etc, and then a publish-friendly flattened one. We can keep both in the same repo to track changes, etc.

My option would be to use SVG+CSS+fontfiles+`<object>`. That is clean and accessible. However, that may require to edit the SVG files by hands, I do not think that the interactive programs give you such a facility...
