### ISSUE TITLE
Examples need fragment identifiers

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/json-ld-syntax#55]
I'm trying to link someone to "Example 48: Language map expressing a property in three languages", but the closest I can get is https://w3c.github.io/json-ld-syntax/#h-note-14 (the note above it).

Given how frequently examples are cited/linked/referenced, it would be super to be able to link to them directly (and ideally in a non-numeric way).

...also browser support for Web Annotations would be nice...

**Comment by gkellogg** [comment]
Maybe a post-processing script that makes id attributes for the examples from their titles, which we ensure are unique. It’s something ReSpec should do.

**Comment by iherman** [comment]
By post-processing I presume you mean a post-processing step as a plugin to respec, right? Shane was a master of doing these things...

**Comment by gkellogg** [comment]
First, I should probably see about a PR to ReSpec to do this. But, we can get a callback from ReSpec and do it there as well. Really, ReSpec should have an option to do this, so that's probably the best bet, but we'll need to wait for it to be released, which shouldn't take too long.

**Comment by gkellogg** [comment]
Fixed in ReSpec version 22.6.0.
