### ISSUE TITLE
New @label keyword

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-syntax#6]
Syntactic sugar for `schema:label` (which doesn’t exist).

Original issue is [JSON-LD 1.1 Feature Request: New @label keyword #371](https://github.com/json-ld/json-ld.org/issues/371)

**Comment by azaroth42** [comment]
+1 to closing. The rdf:type / @type issue is bad enough, no need to propagate @ symbols unnecessarily.

**Comment by azaroth42** [comment]
Closing, won't fix.  Rationale: Unnecessary syntactic sugar.

WG Resolution: https://www.w3.org/2018/json-ld-wg/Meetings/Minutes/2018/2018-07-27-json-ld#section2-4
