### ISSUE TITLE
Typo: @null is not a keyword

### ISSUE THREAD

**Issue by azaroth42** [w3c/json-ld-syntax#60]
> This has been updated to allow (and ignore) @null values.

Should just be "null values".

**Comment by gkellogg** [comment]
Actually, in context, probably `@none`, but they aren't ignored. `Null` can't be used as a key in any kind of index map.

**Comment by gkellogg** [comment]
Fixed in 91ea2585063195ddfe9cfcc006f8f7d3a3ce074d.
