### ISSUE TITLE
Better styling on example buttons

### ISSUE THREAD

**Issue by gkellogg** [w3c/json-ld-syntax#82]
Example buttons could be styled better, and the link to playground should look different from the others which serve to switch example views.

**Comment by BigBlueHat** [comment]
@gkellogg is there anything specific you'd like to see improved here? Or just "better"? 😄

**Comment by gkellogg** [comment]
Generally, just better. If I could have figured out change bars to the left or right, I would have done something like that. We could consider some form of navigation between changes, or an index of changes, but really just a more elegant way to style the changed text would be good.
